### ISSUE TITLE
Group by folder 

### ISSUE THREAD

**Issue by takase1121** [OxygenCobalt/Auxio#10]
#### Describe the feature you want to implement:
It'll be cool if we can group by folder in the library. 

#### Why do you think this will improve everyone's usage of Auxio?
I think that this will be a nice addition. I organize my music in folders, so it'll be nice to play one folder as a makeshift "playlist" before it is implemented. 

#### Due Diligence:

- [x] I have read  [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) and the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Personally having the ability to group by folder doesn't benefit my own usage that much, being someone who already organizes their music by Artist -> Album folders. Plus, adding that new method of organization would increase the loading times heavily due to the app now having to parse and group paths together.

I am planning to add playlists soon however [Maybe in the summer once exam season is over, or even sooner], so it shouldn't be that long. Thanks for the suggestion none-the-less.

**Comment by takase1121** [comment]
no problem!
