### ISSUE TITLE
Add option to not save playback state

### ISSUE THREAD

**Issue by qwerty287** [OxygenCobalt/Auxio#107]
#### Describe the feature you want to implement:

It would be nice if I could delete the playback state if I saved it accidentally. 

#### Is your feature request related to a problem? Please describe:

I'm always frustrated when 🙃 I accidentally save the playback state if I'm in the settings. It would be nice if I could delete it afterwards.

#### Do other music players handle this? If so, how?

I think most do not have a playback state function but do something similar automated in the background.

#### Why do you think this will improve everyone's usage of Auxio?

Because it's a simple quality-of-life improvement I'd say - and it's very easy and could probably added with ~20 added lines.

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
That's a bit easier said than done, as a lot of flows (reloading music, changing the excluded directories) re-save the playback state when they are used. Do you just not want the state to be restored? If that's the case, I can add a toggle for state saving, which should work just fine.

**Comment by OxygenCobalt** [comment]
Oh. So you would be okay if you could just stop playback? I think that's what I'll go for then, as it's the least obtrusive. I'll be spinning up a new issue for my idea and will then merge this issue into that.

**Comment by qwerty287** [comment]
Maybe I don't understand your point, but I'd say it's okay for me to not restore the state if I restart the app, but if I close it but pause/resume from android notification center I'd like to continue with my music.

**Comment by OxygenCobalt** [comment]
Quick question @qwerty287. Would you mind if this toggle simply turns of state *restoring*? In that case, if the toggle was turned back on, Auxio would restore whatever state it had when it was last saved. This is mostly so that I can make a simple implementation that doesn't require me to wipe the state database (which leads to more issues regarding concurrency and such).

**Comment by OxygenCobalt** [comment]
Oh. I've actually been stalling on this issue for awhile since the current idea opens up a bunch of concurrency issues. Clearing it would be much easier

Quick question though @qwerty287: Do you want to clear the state entirely (stop playing, hide the song, and wipe the state), or just clear the current saved state? If it's the former, you are covered by #108, if the latter, it's just another action alongside the existing "Save State" and "Restore State" buttons in settings.

**Comment by OxygenCobalt** [comment]
Okay, I'll do the "Clear state" setting then, since it's closer to where you want.
