### ISSUE TITLE
album dates say 'no date' for FLAC files

### ISSUE THREAD

**Issue by squid-desert** [OxygenCobalt/Auxio#112]
all my albums and songs that are flac files show up as having no date when all of them every single song has a year

**Comment by OxygenCobalt** [comment]
Android doesn't index dates from FLAC files for some reason. I've already documented this in #38. I can't fix this.

**Comment by squid-desert** [comment]
i saw you say in another issue thread something about fixing it by converting to something called soundpod, i don't mean to bug you about an issue that can't be solved, but is there any sorta progress on that if that would solve my problem?

**Comment by OxygenCobalt** [comment]
I have two solutions for this problem:
1. Rework the app by extracting metadata myself, which leads to a slow, terrible UX and/or caching functionality.
2. Rework the app to be based on SoundPod/Subsonic, which is a self-hosted music streaming server. This solves the issue in a way that is probably more future-proofed given how android is progressively neutering their filesystem API, but it also requires the user to set up their own server, which is not ideal.

I've made progress on neither because I really can still go further with the current music loading system. If I were to be honest, both of those additions are "end-game" additions that only happen when I no longer have any of the "basic music player" features like #36 or #72.
