### ISSUE TITLE
[Feat] Covers from the internet

### ISSUE THREAD

**Issue by explosion-mental** [OxygenCobalt/Auxio#125]
#### Describe the feature you want to implement:

Get covers for albums from the internet (MusicBrainz, Last.fm, etc). 

#### Is your feature request related to a problem? Please describe:

no

#### Do other music players handle this? If so, how?

https://github.com/gateship-one/odyssey by fetching some sites, from the readme:
`Artwork support with MusicBrainz,Last.fm, Fanart.tv as artwork provider (Album and artist images)`

#### Why do you think this will improve everyone's usage of Auxio?
Most don't embed the cover into the file itself.
I also saw in odyssey issues about local covers, looks like a challenging (design?) problem.

#### Due Diligence:
- [X] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [X] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [X] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Sadly, I can't add this for a few reasons:

1. I've repeatedly promised that Auxio will *never* fetch information from the internet. I'd rather not break that promise.
2. I don't really like automatic cover art fetching, especially with providers like last.fm that decide to use a single cover instead of the album cover.
3. Adding it doesn't really help with complexity at all. Sure, it removes the insanity of relying on device storage, but I still have to deal with race conditions stemming from cover loading alongside the new issue of handling network connectivity.

**Comment by explosion-mental** [comment]
Not sad at all, I like the `offline` feature of this, just throwing ideas. After many years of listening music by streaming it, I now store them locally and tags them like a maniac. I still don't know about album covers and stuff tho.

**Comment by NMrocks** [comment]
> After many years of listening music by streaming it, I now store them locally and tags them like a maniac. I still don't know about album covers and stuff tho.

@explosion-mental just use an automatic tag editor app like [this one](https://play.google.com/store/apps/details?id=com.serg.chuprin.tageditor), it will save you a lot of time and add album covers too

**Comment by OxygenCobalt** [comment]
Quick addendum here. If I ever add something like Subsonic/SoundPod functionality (Depends on how large my music library becomes and if I built a home server in the future), I may reconsider this, as in that case internet access is justified.
