### ISSUE TITLE
Add support for excluding folders on external drives

### ISSUE THREAD

**Issue by KelvinCrag** [OxygenCobalt/Auxio#134]
#### Describe the bug/crash:

I'm unable to exclude any folder from the music player

#### Expected behavior

Exclude folder from the music player

#### Steps To Reproduce the bug/crash:

1. Go to settings
2. Click on add exclude folder
3. Scroll down to add a folder
4. See error "this directory is not supported"

#### Screenshots:

![IMG_20220520_221229~2](https://user-images.githubusercontent.com/64832927/169613747-e8f36a63-2ea4-49ba-9454-2add6292df40.jpg)

#### Phone Information:

Model: Nokia 6.1 Plus
Android version: Android 10
Skin: Stock Rom

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
That's odd. Auxio does not support external drives like SD cards due to lack of demand, but this whatsapp drive seems to be in internal storage? Can you try this debug APK (rename the extension from ZIP) and take a logcat when you try to add the directory?

To take a logcat, you must do the following:
1. Use a desktop/laptop to download the android platform tools from https://developer.android.com/studio/releases/platform-tools.
2. Extract the downloaded file to a folder.
3. Enable USB debugging on your phone [See https://developer.android.com/studio/command-line/adb#Enabling], and then connect your
phone to a laptop. You will get a prompt to "Allow USB debugging" when you run the logcat command. Accept this.
4. Open up a terminal/command prompt in that folder and run:
	- `./adb -d logcat | grep -i "[DWE] Auxio"` in the case of a bug [may require some changes on windows]
	- `./adb -d logcat AndroidRuntime:E *:S` in the case of a crash
5. Copy and paste the output to this area of the issue.

[app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/8744848/app-debug.zip)

**Comment by OxygenCobalt** [comment]
I've so far received no response, so I will be assuming that this is a request for external drive excluding support and converting the issue as such.
