### ISSUE TITLE
Support encrypted external sdcard

### ISSUE THREAD

**Issue by lamyergeier** [OxygenCobalt/Auxio#141]
I am using the latest version of Auxio from f-droid 2.2.2. I have Samsung A70 running Android 11. My 256 gb sdcard is encrypted by Samsung using my pin. Does Auxio supports this? The app remains blank and does not recognize any music fille. Other open source app like vinyl Player works fine! 

Even reload music option does nothing! 

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Sadly, I do not have a Samsung phone and have no way to emulate the same feature. Can you show me screenshots of Vinyl Music Player and Auxio so that I can try to narrow down the issue?

**Comment by lamyergeier** [comment]
[cid:eu.faircode.email.319]

[cid:eu.faircode.email.320]

28 May 2022 14:55:57 Alex ***@***.***>:

**Comment by lamyergeier** [comment]
![Screenshot_20220528-151548_Vinyl Music Player](https://user-images.githubusercontent.com/42092626/170829660-380a1ecb-ffa0-432d-8b09-31d7032156ed.jpg)
![Screenshot_20220528-162751_Auxio](https://user-images.githubusercontent.com/42092626/170829684-8db77c4a-9104-490e-8854-bfebd367220d.jpg)

**Comment by OxygenCobalt** [comment]
And you see no message like "No music found" or "Music loading error"? In that case, Auxio's music loading system is hanging entirely.

**Comment by lamyergeier** [comment]
No error is shown. Previously when the music was in internal memory then, auxio was showing them correctly.

28 May 2022 21:12:34 Alex ***@***.***>:

**Comment by OxygenCobalt** [comment]
Can you confirm that if you use a *decrypted* SD card that Auxio still functions? I need to narrow down whether if it's related to external storage or encrypted storage.

**Comment by lamyergeier** [comment]
Before encryption it did work from external sdcard.

28 May 2022 23:18:12 Alex ***@***.***>:

**Comment by OxygenCobalt** [comment]
Can you confirm that Vinyl music successfully reloads music and does not also hang? I can't tell if it is simply using cached music that it already scanned from a decrypted SD card.

**Comment by lamyergeier** [comment]
I rebooted my device, i got the same results. Does that answers your question?

28 May 2022 23:49:31 Alex ***@***.***>:

**Comment by lamyergeier** [comment]
I rebooted again but this time Auxio also loaded the music after some time.

29 May 2022 06:36:48 Lamyer Geier ***@***.***>:

**Comment by OxygenCobalt** [comment]
Okay, this is starting to seem like a Samsung issue, not an Auxio issue.

More specifically:
- When you originally encrypted the SD card, the OS for made any `MediaStore` query hang instead of succeeding. This would effect both Auxio and Vinyl. 
- The only reason Vinyl worked is that it has already cached music it has loaded, so the music remained accessible. Auxio does not do this since it's not really needed.
- When you rebooted the OS, apparently it could properly initialize `MediaStore`, so Auxio could index music again.

Issues like this are far too common for Samsung phones. They deliberately cripple external media apps in order to make you use their built-in media apps (which are infested with ads and tracking). Sadly I doubt there is anything I can do about this flaky behavior.
