### ISSUE TITLE
Playback speed support

### ISSUE THREAD

**Issue by Flippette** [OxygenCobalt/Auxio#146]
#### Describe the feature you want to implement:

A playback speed slider with presets (i.e. 0.75x, 1.25x and 1.5x)

#### Is your feature request related to a problem? Please describe:

Personally I enjoy some tracks at 1.5x and I miss the ability to speed them up after moving from VLC.

#### Do other music players handle this? If so, how?

VLC has this in a 3-dot menu.

#### Why do you think this will improve everyone's usage of Auxio?

Some people might have preferences as to how fast they like their music.

#### Due Diligence:
- [v] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [v] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [v] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Sadly, I don't think I'll add this for the same reason why I don't implement an equalizer [#113]. I don't fiddle with my audio too much, so I don't [get any benefit](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) from such a feature. Sorry.

**Comment by Bnyro** [comment]
I would like to add that this would be quite a useful feature to me, especially for listening to downloaded podcasts, voice recordings, ... And indeed it would make sense to add an option for the pitch in the same, since the `ExoPlayer` handles both of them via `ExoPlayer#setPlaybackParameters`. Nevertheless the pitch option isn't mandatory to be added in my opinion, only playback speed as an option would be sufficient for me personally and probably for most users.

I would be happy to open a PR for that being added as a button to the dropdown menu in the player screen which would open a dialog that has sliders for the playback speed and the pitch.
However I want to make sure it would be accepted first :)

Of course I'd also respect being rejected here since I'm not the maintainer of the project and do really value all the efforts spent into the project (and your @OxygenCobalt's issues at the Material Components Android repo, which have already been useful for me multiple times ;) )

**Comment by NBA613** [comment]
Hoping this can be reconsidered at some point. Playback speed control is very useful for podcasts as mentioned...
Thanks for great app!

**Comment by OxygenCobalt** [comment]
I've spoken about this in other points, but I generally don't design Auxio with the intent of playing podcasts. A program should do one thing and do it well, I don't want to shoehorn podcast-specific functionality that will not be used in a music context, or vice versa. Sorry.

**Comment by e-t-l** [comment]
> Sadly, I don't think I'll add this for the same reason why I don't implement an equalizer

It's been a few years, and I see that the app has an Equalizer now. Have you reconsidered playback speed control too? (I see references in the source code to "speed dial" so I thought maybe you had already added it, yet I cannot find a anywhere in the app to change playback speed...)

**Comment by NearestWater262** [comment]
@OxygenCobalt can you please reconsider this? also add a pitch adjuster i love having this feature in Newpipe and i love hearing music sped up and slowed down. the millions of nightcore and tiktok sped up videos on youtube is proof that people want this

**Comment by OxygenCobalt** [comment]
Not really. I outsourced equalizer functionality to the system since it means that the maintenance burden of it isn't that high (a few loc) and so even if I don't use it it's unlikely to break.

Meanwhile playback speed is a more complex thing (UI integration + impl) that I also won't use, so it'll just rot and break over time. My bandwidth as a maintainer is already heavily strained so I can't really add something like that. Sorry. @NearestWater262 @e-t-l 

(Also sorry for the delay)
