### ISSUE TITLE
can't exclude download folder

### ISSUE THREAD

**Issue by theotheroracle** [OxygenCobalt/Auxio#148]
#### Describe the bug/crash:
the download folder cannot be allowed full access, making it unable to be selected

#### Expected behavior

the download folder can be excluded from the library
( vinyl solves this by integrating a folder picker )

#### Steps To Reproduce the bug/crash:
settings > excluded folders > add > downloads

#### Screenshots:

![Screenshot_20220604-185849_Files](https://user-images.githubusercontent.com/20211219/172021893-cd66e71b-b0d0-40b7-bb90-4346de5afa10.png)

#### Phone Information:

oneplus 7t
lineage 18.1, android 11

#### Due Diligence:
- [ x] I have checked this issue for any duplicates.
- [ x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [ x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Android 11 adds restrictions on what kinds of folders you can exclude. There is nothing I can do about it.

**Comment by theotheroracle** [comment]
if the download folder is the only folder that can't be shared, could it not be excluded with a toggle ?

**Comment by OxygenCobalt** [comment]
Technically, yes. In practice, Android disables accessing of other directories. I guess the only thing I could do would be to allow someone to directly input a directory path.

**Comment by theotheroracle** [comment]
theoretically you could also just allow hiding albums since it groups unknown 
songs in an album named after the folder its in

**Comment by OxygenCobalt** [comment]
I rejected that back in #99, as it was too similar to excluding folders.

**Comment by MagicRB** [comment]
Btw @theotheroracle if you have a rooted phone with edxposed/zygisk, it quite is to patch out. That restriction, just grep the android source for the messageit gives you and then figure out how to use either zygisk or edxposed

**Comment by Mrnofish** [comment]
> There is nothing I can do about it.

Actually i think you can do something about it.

The only.reason for me to want to exclude download manually is because auxio won't allow setting a root folder.

If I could set the root to Music then I would not need to exclude manually a ton of different folders, only folders under the music folder which need

**Comment by OxygenCobalt** [comment]
Could you not have a sub-folder containing your actual music and then simply include that @Mrnofish. Internally there must be separate modes for include/exclude since the query may fail if they were used in parallel.

**Comment by Mrnofish** [comment]
So `/sdcard/Music/No wait, REAL music` ?

I guess that hack would sidestep the problem, but having to change the way the data is stored so that the software doesn't get inconvenienced is a little ugly.

> Internally there must be separate modes for include/exclude since the query may fail if they were used in parallel.

You certainly have a better grasp on how the app and Android work internally, however it seems to me handling both inclusions and exclusions should be neither unfeasible nor hyperbolically complex.
