### ISSUE TITLE
Grid view for albums

### ISSUE THREAD

**Issue by missyraja** [OxygenCobalt/Auxio#156]
#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
I've already rejected this beforehand due to how vulnerable it is to scope creep. Adding this as an option would not only have to apply across much of the app, but it also opens the door for a bunch of other item customizations. Eventually you end up with something like Retro where there are 12 display options that all are slightly inadequate in some way. I prefer sticking with one layout, but if I were to add this, it would almost certainly be an opinionated setting applied universally.
