### ISSUE TITLE
Fast scroll inside genres/artists/albums

### ISSUE THREAD

**Issue by illdeletethis** [OxygenCobalt/Auxio#166]
The scroll bar on the side is quite useful, but so far only exists for the tabs, not the categories within them.
While it is not overly common for albums or even artist discographies to reach extents where this is necessary, genres can easily contain a substantial number of elements without being separable in a sensible way.
Therefore i"d like for any category exceeding 100 elements to get the scroll bar too.

**Comment by OxygenCobalt** [comment]
I don't see why not. It would make the app more consistent anyway. I could probably extend this to the queue too after #92.

**Comment by OxygenCobalt** [comment]
Actually, I don't think I can do this as it stands. All fast scroller implementations assume consistent item sizes, but since the size of items in the detail views are in-consistent (Item details, headers, albums, songs, etc.), this leads to a bunch of bugs that are impossible to fix without killing performance. The only solution for such would be a total rework of the detail UI to rely on a collapsing toolbar instead of my (superior) emulation of that behavior, which I can't really gague the feasibility of. Sorry.

**Comment by illdeletethis** [comment]
This is quite unfortunate.
It not being length dependent and without indicator would have both been fine.
From what i can tell the only thing not one regular line high is the top area with image, information, play buttons and sorting, would it work if that area got treated as the number of regular lines that adds up to the height of that area?

**Comment by OxygenCobalt** [comment]
No, I don't think so. For one, the main header not the only thing making the calculations disjoint (there are also sub-headers for albums and songs). Also, I could not reliably get the height of those UI elements as they may not exist. For example, "Get Item 1 and 2" might return the main header and a "songs" header, or it may return two songs, depending on the scroll position.

Hard-coding sizes is a no-go as well, as user-defined text scales would throw off the actual sizes of the views. 

I am extremely sorry about this. Maybe in the far future I'll be able to do this, but I don't see it as it stands.
