### ISSUE TITLE
About widget

### ISSUE THREAD

**Issue by AnujMehto** [OxygenCobalt/Auxio#167]
So i have been using this app I'd say this is the best offline music app but i do want to use the widget for quick access to the music but the widget look kinda old not complaining just suggesting you can make the corners circle and i have a cool idea about how to make the widget the idea is make it square then the song is playing the widget background should adapt to it then the controls should be over the song and pls try to make it clean

**Comment by OxygenCobalt** [comment]
> The widget looks old

This is expected. The widget APIs are **terrible**, even more so before Android 12. You are restricted to effectively the subset of UI components that Android had in 2011, and thus they are stuck in 2011.

> you can make the corners circle

**Comment by OxygenCobalt** [comment]
> The widget looks old

This is expected. The widget APIs are **terrible**, even more so before Android 12. You are restricted to effectively the subset of UI components that Android had in 2011, and even then you can only do so much to improve the view. This, most widgets end up looking like they came straight out of 2011.

Generally, I wanted to make Auxio's widget fit in with the sharp corners and Lollipop-isms that most widgets have to deal with. So, below Android 12, sharp corners are the default.

> you can make the corners circle

To do this, I would have to round the album covers. Since I hate rounded album covers, this would have to be tied to a particular setting, probably the existing "Rounded album covers" option. It's not out of the question though.

> i have a cool idea about how to make the widget the idea is make it square then the song is playing the widget background should adapt to it then the controls should be over the song and pls try to make it clean

I'm not fully sure what you want here, but it seems complex, and any sort of complex UI behavior with widgets is impossible. Again, the widget API is too restrictive.

**Comment by OxygenCobalt** [comment]
Okay, I'll try to implement rounded corners in the widget. It will be tied to the "Rounded album covers" option (Which will likely be renamed to "Round mode" given how the setting is beginning to extend into the UI).

**Comment by AnujMehto** [comment]
Nice and i have been using this app for weeks now and i also want to give a
feedback see i have use 3-4 music apps and this was the smoothest but i
like you to add some basic features - 1. While sorting songs there isn't
any type of sorting so we can see which song was added when 2. I also want
a option where you can make your playlist this is actually useful i have an
realme phone and the inbuilt music player was good but not smooth so also
include the playlist option 3. Sleep timer (optional) i don't see myself or
anyone using this feature too much but hey it's good to have little
features. Yes this are pretty much it i know this will be hard but making
an app that is better then others can show how good devloper are you

**Comment by OxygenCobalt** [comment]
@AnujMehto thanks for those suggestions:
- For the first one, I think you are talking about a "last added" list? I do not benefit from such, so I won't implement it.
- Playlists are tracked by #36.
- I do not benefit from sleep timers, so I won't be implementing it.

**Comment by OxygenCobalt** [comment]
2.5.0 maybe

![Screenshot_20220701-201038_Trebuchet_1](https://user-images.githubusercontent.com/65370175/176982996-bc46f42f-fc4a-46f2-8097-5e5f6af51164.png)

**Comment by AnujMehto** [comment]
When are you going to publish it? Version 2.5 man i am waiting 😗 and pls
add last added sorting option

**Comment by OxygenCobalt** [comment]
2.5.0 is released. You can enable a rounded widget by enabling "Round mode" in settings.
