### ISSUE TITLE
Bottom navigation bar

### ISSUE THREAD

**Issue by Naverim** [OxygenCobalt/Auxio#173]
#### Describe the feature you want to implement:
A bottom navigation bar
![unnamed(1).png](https://user-images.githubusercontent.com/103884904/175754600-c8085546-9bc3-42f3-ae4a-33c438657497.png)

#### Is your feature request related to a problem? Please describe:
Im frustrated on how everytime I want to switch to a different tabs, I gotta use my second hand to press it because it's at the top

#### Do other music players handle this? If so, how?
Retro music player has bottom navbar

#### Why do you think this will improve everyone's usage of Auxio?
A better one handed experience

#### Due Diligence:
- [✔️] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [✔️] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [✔️] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Auxio used to do this before I removed it in 2.0.0 for several reasons:
1. Since Songs, Albums, Artists, and Genres are all semantically related, it is actually the correct guidance to use a tab layout and not a navigation view.
2. Navigation becomes far more in-coherent, as there simply are not enough slots to fit every destination in the app on a navigation bar (The max is 5).
3. You can just swipe to your destination without having to reach to the top bar.

Not adding this, sorry.
