### ISSUE TITLE
Current Song is not always updated properly in Media Notification

### ISSUE THREAD

**Issue by jpohlmeyer** [OxygenCobalt/Auxio#179]
#### Describe the bug/crash:

I have noticed that on my device the currently played song is not updated correctly in the media notification all the time.
Every few songs, the song displayed in den media notification does not update when I skip to the next song.
I tried debugging the issue for some time, but could not quite figure out where it might be coming from.
However, what I noticed is that if I just call `target.onCompleted(null)` in the `BitmapProvider.load()` call and return after, the issue did not present itself (there was however no cover shown for obvious reasons).

The issue was already present when I started using the app with version 2.3.1 and it persists in 2.4.0 and current dev branch.
As I have seen that you reworked the bitmap loading in 4a79de455a9f2f35caa2e9dd3e52929dc3333df3, I also tried e785f5a3a5a8641646e036621ea34b5fa3123c40, but the issue was present here as well.

#### Expected behavior

Currently played song should correspond to the song shown in the notification.

#### Steps To Reproduce the bug/crash:

1. Play music.
2. Skip until the song is not updated properly.

#### Logs/Stack Traces:

--

#### Screenshots:

--

#### Phone Information:

Pixel 4a running Android 12
Pixel 4a Emulator running Android 12

(On the Pixel 4a Emulator running Android 11 the problem did not seem to be present)

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I need more clarification:
- Are you skipping fast enough to cause the notification to not update? Or does the notification not update, even when you skip slowly? The former is intentional behavior in order to avoid race conditions.
- Do your songs have album covers or not? This might help me narrow it down a little.

**Comment by OxygenCobalt** [comment]
And this is just in the media notification? This doesn't occur to the widget at all?

**Comment by jpohlmeyer** [comment]
The widget updates properly every time.
In the media notification i sometimes see the bypassed song flicker when it updates to the new one after skipping further.
Sometimes the media notification also seems to just fall behind and displays the previous song for 2 or 3 songs.
Debug log prints in the `BitmapProvider.load()` function confirm that that the metadata update should happen with the right song.
I have tried playing the same files in the VLC app and I did not encounter this behaviour, but they might do things different anyways.
Could there be a race condition in the android implementation that updates the notification before the metadata is updated?

**Comment by OxygenCobalt** [comment]
No. I deliberately designed it to update the notification in it's entirety before updating the notification.

It's starting to seem like my notification is being rate-limited. Can you confirm with the debug logs that [this function](https://github.com/OxygenCobalt/Auxio/blob/e883336b04b7dc88f2d07101da3110e721303fd2/app/src/main/java/org/oxycblt/auxio/playback/system/PlaybackService.kt#L313) is being called properly? If it is, then this is an insane android issue.

**Comment by jpohlmeyer** [comment]
Yes this is being called every time I skip a song, even if the notification does not update.

**Comment by jpohlmeyer** [comment]
The issue is still present in this version. I noticed that sometimes just the cover updates, but not the rest of the notification (artist and songname). This is not specific to the APK version, but also happend with the other version.

**Comment by jpohlmeyer** [comment]
I downloaded some random mp3 music files from freemusicarchive, no items have album covers. I tried those and the error still occurs. Seems it does not have anything to do with the album covers in particular but maybe the async loading of the covers?

**Comment by OxygenCobalt** [comment]
If `startForegroundOrNotify` is being called (as it is), the cover was loaded, and it should update the notification. This is in all likelihood yet another insane android problem.

I will entertain your guess about cover loading. Here is an APK where I downsize the cover to a small size.
[Auxio_Covers.zip](https://github.com/OxygenCobalt/Auxio/files/9031525/Auxio_Covers.zip)

**Comment by jpohlmeyer** [comment]
Still the same unfortunately.

**Comment by OxygenCobalt** [comment]
Okay, that leaves me with one final option: Copying the notification in it's entirety. If this does not work, I'm going to conclude that your SystemUI is busted and fails to correctly handle media notifications.

[Auxio_CloneNotif.zip](https://github.com/OxygenCobalt/Auxio/files/9031629/Auxio_CloneNotif.zip)

**Comment by jpohlmeyer** [comment]
No luck here as well. The issue does not appear on your end even in the android emulator? At least I am not the only one confused by this issue :see_no_evil:

**Comment by OxygenCobalt** [comment]
Yeah, I have never come across something like this. You say it only occurs to some of your MP3 files. Can I have some of them?

**Comment by jpohlmeyer** [comment]
It seems pretty random and it is not always the same files. Sometimes the same file works and sometimes it does not.
I can definitely upload the files I used in https://github.com/OxygenCobalt/Auxio/issues/179#issuecomment-1172690723.
[freemusicarchive.zip](https://github.com/OxygenCobalt/Auxio/files/9031769/freemusicarchive.zip)

**Comment by OxygenCobalt** [comment]
**I just reproduced the issue.** It seems to only exist in the stock Android 12 ROM. The Pixel variant (Which I use) seems to not suffer from it. I hate this platform so much.

**Comment by OxygenCobalt** [comment]
Okay, I think I understand the issue now. Something about stock Android 12 builds make them absurdly vulnerable to race conditions that make the notification state incorrect. Every OEM fixes this issue, and it seems to be resolved in Android 13 by reworking the notification to rely on the media session.

Worse still, while Auxio's async loading is great for efficiency and smoothness, it seems to worsen this race condition. VLC does not have this issue because it loads covers in a blocking manner. This is bad for smoothness, but also reduces this race condition to only when the skip button is pressed in rapid succession. Similarly, disabling `BitmapProvider` will also resolve this issue in the same way, albeit even more effectively since it makes the callback instantaneous. 

I doubt I can fix this. I would probably reccomend the following:
1. Use the Pixel Android 12 ROM. I can confirm that it does not have this issue since I use it on my Pixel 5.
2. Wait for Android 13 to circulate into the Ungoogled ROM sphere. This will also likely resolve this issue, as it changes the media notification to rely on the media session (Which is an amazing change that makes so much more sense, thank god).
3. Turn off the "show covers" setting and live with no album covers being shown until you can do #2.

I am so sorry about this. As alanorth said in #129, "Android is ghetto as f***".

**Comment by jpohlmeyer** [comment]
Yeah I figured it might be complicated. I am using the standard provided Pixel image on my Pixel 4a though (Build number: SQ3A.220605.009.A1), but maybe I just got unlucky.
Thanks for taking your time to try to figure out the problem with me nonetheless! 
I will disable album covers for now and hope for it to be no issue with Android 13.

**Comment by jpohlmeyer** [comment]
The `Show album covers` setting seems to only deactivate the actual image being loaded and shown however but the callback in `BitmapProvider` is not bypassed. Can you check the setting in `BitmapProvider.load()` and bypass the async request e.g. like this?
```
if (!settings.showCovers) {
    target.onCompleted(null)
    return
}
```

**Comment by OxygenCobalt** [comment]
The async request pretty much a no-op when cover loading is disabled (No `withContext` calls, cache searching, or long-running work). Time-wise, it is identical to the check you proposed.

As for your build. That is my build too. The more I look into this the more it feels like an insane rate limiting issue. The notification state is consistent. It should be updating. All my race condition mitigations work. I have no idea why this is happening.

**Comment by jpohlmeyer** [comment]
From what I figure there might be some scheduling or whatever going on, because bypassing the async request when covers are disabled and instead do a sync call to `target.onCompleted()` seems to solve this issue for me. When just disabling the album covers it is still broken. I can also make a pull request with my change if you want to.

**Comment by OxygenCobalt** [comment]
I think I may or may not have figured it out. Starting in Android 11, google has been silently extending how much it "filled in" the notification with media session metadata. I used to think this was just the album cover, but it now seems like IT WAS THE ENTIRE SET OF METADATA. TITLE AND ARTIST.

This change was not documented. At all. Worse still, if you did not realize this (like me) and tried to update the metadata, it led to what seemed like a race condition but what was actually the mediasession OVERWRITING IT'S OWN STATE ON THE NOTIFICATION BEFORE IT WAS POSTED, WHICH WOULD STILL BE THE OLD SONG BECAUSE OF ASYNC COVER LOADING. 

VLC worked since it targets API 29, which does not have this. It did not happen to me because, again, race conditions. I really want to scream right now.

This means I have to tie the notification AND the media session together in a very bad no-good compat class that updates both simultaneously depending on the version and THEN tells PlaybackService to update the notification.

**Comment by jpohlmeyer** [comment]
No worries, at least I now know that it was not just me going insane.
I may have a look at this and if I can follow the problem you are describing, but for now I have a local version that for the time being does not appear to run into this problem on my device (albeit without covers).

**Comment by OxygenCobalt** [comment]
Willing to try this APK? I am unable to completely fix the issue (Again, notification rate limiting is weirdly harsh), but the issue does not seem as apparent now. It now only seems to be triggered by notification rate-limiting and not average skipping.

[Auxio_LessBrokenNotifications.zip](https://github.com/OxygenCobalt/Auxio/files/9033604/Auxio_LessBrokenNotifications.zip)

**Comment by jpohlmeyer** [comment]
Wow yes that seems to solve it for me! I have skipped for quite some time now in this version without any problems.

**Comment by OxygenCobalt** [comment]
Wow. Amazing. Thanks for holding out this long.

**Comment by jpohlmeyer** [comment]
Thanks for fixing! Really glad I found this app.
