### ISSUE TITLE
Please revert the Outlined Material Icon style to Filled

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#187]
#### Describe the feature you want to implement:
Add fill to material design icons throughout the app.

#### Is your feature request related to a problem? Please describe:
Problem: Outlined icons look awful

#### Do other music players handle this? If so, how?
They use filled material icons

#### Why do you think this will improve everyone's usage of Auxio?
Because they won't have to look at the awful outlined icons

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
   
#### In all seriousness
Outlined material icons are awful. Atleast i feel that way. In my honest opinion, Filled rounded icons are much more visually soothing than outlined, unrounded icons. Material design guidelines doesen't specify that you need to use outlined icons.    
Why are outlined icons bad:
- they have hollowed out parts where they don't need to be hollow
- they add unneded complexity where not needed
- they look unnecessarily sharp and agressive (scary) while rounded filled icons are comfy
    
![image](https://user-images.githubusercontent.com/21956756/179366787-759df7ea-0733-4c72-89f8-dc18bc4c0a6e.png)
> i would be really glad if you could use the filled, rounded icons instead of outlined ones. Thanks a lot.
> this issue is not a joke i have a burning hatred in my heart against outlined icons i tried to convey this feeling as professionally as i could.

**Comment by OxygenCobalt** [comment]
It's now [recommended](https://m3.material.io/styles/icons/applying-icons) by the material design guidelines for me to use outlined icons. This is because they tend to work best in denser UIs and on other screen sizes. Filled icons are only to be used to represent "active" states, like a selected icon in a navigation bar.

Currently, I use the sharp outlined icons. Guess this was force of habit, since I chose sharp back when Auxio was a completely-sharp app. However there are *rounded* outlined icons I could use.

![image](https://user-images.githubusercontent.com/65370175/179367573-72865787-097d-4744-a884-79a4cbe9a7b7.png)

**Comment by KraXen72** [comment]
Yes that's better than nothing. Please atleast use the rounded ones.
Also, why is the icon weight different for shuffle, repeat vs. play and skip?

**Comment by KraXen72** [comment]
![image](https://user-images.githubusercontent.com/21956756/179367696-477492ba-085a-438e-a3ce-781f35085586.png)
but like do the filled icons not look 1000x times better?? (maybe its just me tho)

**Comment by OxygenCobalt** [comment]
According to the new guidelines, aside from filling the icon, I can also use "grade" to represent an icon's activation state, which will slightly thicken it. I chose to do this since it would allow me to unify how the shuffle/repeat icons were represented across the app (Previously there was two styles, an indicator and a faded icon).

I'm largely in-different towards iconography. It seems like your biggest annoyance is with the play and skip icons. I could fill those in, but keep the new icons elsewhere.

**Comment by KraXen72** [comment]
Oh yeah hell yeah the play and skip buttons would change like night and day thanks!!!!

**Comment by KraXen72** [comment]
and according to the grade, i looked into the guidelines, and it makes sense *i guess* but i still think just faded vs. fully opaque was more stylish & better conveyed what is going on. like fading out unused buttons/icons is a universal ui/ux concept that's been around for ages, and it's used in multiple design languages, not just material design. Google ~~shits on design~~ sorry sits down and designs this whole new update to their design language, which is really good for the most  part but i wouldn't say it's perfect. 

If you wanna stick to the guidelines with the icons grade, fair enough, as that's probably easier to maintain, but if you're indifferent towards iconography, i'd like to see what other people think about this "icon grading" by google and maybe decide on that? (as if to keep the old graying out?)

**Comment by KraXen72** [comment]
oh, i just noticed, you already have gray color when the icons is not used, and purple when it's in use. I think that's enough distinction?? (no need for grade) maybe add the dot under active icons as you had, it was stylish.

**Comment by OxygenCobalt** [comment]
The issue with the normal control + activation coloring was that one some devices, it was too indistinguishable, hence the indicator. I could not replicate such elsewhere, however, so the design of repeat/shuffle was disjoint between the indicator and grayed icons. The issue with grayed icons is that gray can convey both "inactive" (Like you said), but also conveys "disabled". I want to minimize confusion in that regard.

**Comment by KraXen72** [comment]
Okay. Well if you could atleast round the outlined icons and fill in + round ⏮⏯⏭ icons, it would be really good.
Thanks.

**Comment by OxygenCobalt** [comment]
Okay, I'll definitely fill in the play/pause/skip icons and see what I can do with the others.
