### ISSUE TITLE
(Question) What's up with the new typography?

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#188]
Like i get that it was meant to be more in-line with material design guidelines, but why is stuff so tiny???

see:
before (nice, filled and rounded font):
![image](https://user-images.githubusercontent.com/21956756/179367207-94609a47-3964-4e1e-b126-41c7cdc789f4.png)
  
 after (tiny, sharp font?????):
![image](https://user-images.githubusercontent.com/21956756/179367200-a53ac414-a332-4e0a-8790-21ee9133e5b9.png)

**Comment by KraXen72** [comment]
no idea if it's visible from the screenshot maybe just the font-weight alone on the artist made it feel really wierd

**Comment by KraXen72** [comment]
i'd love if you would use the same font for song title and artist, but i get that  you want to go more in-line with material design typography.

**Comment by KraXen72** [comment]
(Maybe unrelated but not sure if i should open a  new issue): why did you remove the: artist (bullet) album display mode? added information density is always good (if it looks good also which it does). Like if concating 2 strings was buggy/non-reliable, just split it into 3 elements:
| artist | | . | | album |

**Comment by OxygenCobalt** [comment]
A few answers on this change:
1. Letter spacing. Previously, I used letter spacing derived from Roboto, with some mild tweaks to "look right". Now, I use the letter spacing that is "recommended" with the inter font.
2. I made some of the "Label" styles use the lighter font. This is to make it more consistent with the rest of the app (Bold header, unbolded sub-header). The "new" style is actually consistent with the way Auxio styled the playback bar pre-2.0.0. 
3. I removed the bullet display mode since the ellipsis were applied too often. There wasn't any bugs, I just wanted visual clarity, especially in list items where I'm planning to add a button eventually.

**Comment by KraXen72** [comment]
fair enough. it kind of feels "off" now, but i bet i'll get used to it. I looked at the screenshots of pre 2.5.0 and 2.5.0 really closely and most of the "off" feeling comes from the font weight: it the bolder font made the text look more comfortable. So if you could at least tweak/revert the font weight, i would be glad, but it's a pretty minor thing tho so it's fine.

**Comment by OxygenCobalt** [comment]
I'll look into other variants of Inter to see if I can increase the weight of the smaller sizes.

**Comment by KraXen72** [comment]
Thanks a ton!!
