### ISSUE TITLE
Add support for lyrics

### ISSUE THREAD

**Issue by mariobrostech** [OxygenCobalt/Auxio#19]
#### Describe the feature you want to implement:
I would like for Auxio to have an option of displaying both synchronized lyrics (using a .lrc file) and unsynchronized lyrics while playing a song.

#### Is your feature request related to a problem? Please describe:
My feature request is not related to a particular problem.

#### Why do you think this will improve everyone's usage of Auxio?
A lyrics view in Auxio would greatly benefit those who enjoy singing to their music or would otherwise want to view lyrics embedded into their song's tags or stored in an external file.

#### Due Diligence:

- [x] I have read  [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) and the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This doesn't benefit [my usage](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md#feature-addtions-and-ui-changes), as most of my music is instrumental and wouldn't need a lyrics view. Sorry.

**Comment by OxygenCobalt** [comment]
@nitinsooni

(Warning: This is going to get technical and ranty. I don't mean to insult you or anything, I just want to make out my point)

Yes, at any point I could just go wild and copy someone elses implementation into my project. Zyrouge has done some cool stuff with symphony. But consider:
- How do you switch between the two views? Can't but a button anywhere without obscuring something (like the cover), violating design specifications (3+ buttons on the toolbar). Hiding behind a gesture wouldn't work, and trying to haphazardly cram it next to the shuffle button or shove it in the queue bar also don't really work. This has to be done right, otherwise it's clunky and unusable UX.
- Does it scroll properly? What happens when you rotate the device? What happens when the bottom sheet needs to restore it's state? What about the queue? Is it jittery? Does it stop syncing the moment you even slightly poke it? Do you have to add another toggle to switch from sync or unsync?
- How are you getting the lyrics? last.fm is non-free. I can't parse most lyrics tags without future drastic reworks. LRC files in particular require broader file access. No, requesting legacy external storage doesn't work. Lyrics come from crazy sources and formats that are nearly impossible to reconcile too.
- How does the code actually integrate? Where did you put it? Did you put it in the fragment? The activity? A global variable at the top of a file? Did you make a shared object? Is it in a service? Is it extending ExoPlayer? How should it slot in next to PlaybackStateManager and ExoPlaybackStateHolder and PlaybackViewModel and MediaSessionServiceFragment? How does it handle asynchronously loading tasks? How does it slot in with music loading? Are you caching lyric tags? Symphony uses entirely different conventions from me, JSON and Boxes and Jetpack Compose over SQLite Databases and Repositories and Android XML. It isn't easy to port.
- How are you synchronizing live lyrics? It has to be exact timing, the position on the seekbar is updated not as often as you think. That means you need to interface and extend ExoPlayer. You also have to make sure all of the state is properly hoisted upwards so that the UI reflects it and wont break if you rotate or navigate or swipe the bottom sheet or scroll around or click on other components or open it after a warm start or restart the app or if a playback state restore fails or

This is a subset of what I have to consider with lyrics. It doesn't matter if someone else did it in kotlin. It is *that* complicated. And I won't use it personally, so it will just rot over time and break more and more. Sometimes I can go weeks without being able to make a single-line fix since I'm just one guy with obligations outside of life. I can't maintain features I don't gain benefit from, and that's the core thesis of why I reject so many feature requests.

I mean, look at Retro Music. It's not maintained anymore. It's stuck on API 29 or so due to unmaintainable scoped storage and low-level API hacks for features *like lyrics*. There's too much burden, too many features, too much complexity from extremely complicated features *like lyrics.* I struggle with architectural difficulties with Auxio even with it's reduced feature set. Even symphony is buckling under it's rapidly increasing weight. Gramophone will meet the same fate as well with how quickly they are adding features. I don't want Auxio to die, and if that means I don't have as much stuff, then fine.

If you want to fork Auxio and add everything that I don't want, then more power to you. Maybe you will have the time and motivation to maintain it where I just can't. As it currently stands though, even a fully-baked lyrics implementation is not going to be brought in. Sorry.

**Comment by zodywoolsey** [comment]
if i write a PR for this feature myself and offer to maintain it myself, would it be possible for me to get it in? i would probably ask for some minor onboarding as well so i can stay within the goals and codestyle of the project.

**Comment by saladnoob** [comment]
It's a shame that this isn't a feature. Though, I appreciate your efforts to maintain Auxio it has clean UI with great Material 3 design and customizability, I love those unique features that some music players may not have, love that shit bro. The amount of open issues is frying me lmao. But I'd like to answer your questions **(take this with a grain of salt, I'm a vibe coder and I don't understand developing Android apps)**:

Switching between to lyrics view, since the queue is on the bottom sheet, it could be similar to YouTube Music, with tabs next to the queue. It probably won't go against Material Design (I haven't even read the guidelines). Ideally, it should scroll smoothly, cause of those guidelines I haven't read. You could not allow rotation, though I think material 3 is for adaptability for any screen size like tablets or foldables. For me, just place the bottom sheet on the right and the album cover on the left with the buttons. If the bottom sheet needs its state restore, can the app just store the changes and saved as persistent storage for when closing or closing the app? The queue should be on the right of the lyrics view, Idk but its weirdly fitting there, hierarchy-wise similar to Apple Music's lyrics on left and queue on the right. This makes sense, majority of people read left to right. And all though, the queue's important, lyrics are as important or even more important (also being at the bottom sheet makes it easy reach, ergo better UX). "Is it jittery?" Clarify? _ples_ :>. There should be Auto-scroll to synced lrc of course, but if the user touches even a little stop Auto-scrolling. Continuing Auto-scroll you two options: A button to continue, and if the user is inactive in scrolling for an amount of time then continue. Adding another toggle to switch between sync or unsync might be too much, maybe sync or unsync depending if LRC is one of those would be better. For getting lyrics, some users like me, get them from places like lrclib or make their own LRC files. Supporting embedded lyrics or local .lrc files. Technical aspects are definitely tough problems to solve. I'm not really aware in developing of Android apps, I just hope for a solution that guarantees app stability. Synchronizing live lyrics or Word-by-Word lyrics, is a difficult format there different versions of lyrics files. I've used Songsync and Lyrically, the latter might be obscure but essentially they use different versions for Word-by-Word or syllable version of LRC. You can get a way with implementing synced lyrics only.

I understand you've thought it through with these problems. It's a balance maintaining and adding features such as this as developer. I completely understand if you'd not implement this feature. It's a technical challenge. I'm not asking btw, just ranting also. **No pressure.**

**Comment by proItheus** [comment]
If someone want an auxio with lyrics: [my fork](https://github.com/proitheus/Auxio) added that. It's rather sloppy code and UI, and is nowhere near "production quality" or sth. But it works, and I'm using the lyrics feature in it daily, so it'll be maintained for now. You can download the debug build from github actions.
