### ISSUE TITLE
Lyrics

### ISSUE THREAD

**Issue by xmha97** [OxygenCobalt/Auxio#190]
Please support id3 embedded lyrics and .LRC files.

**Comment by KraXen72** [comment]
pretty sure this was already requested and denied because out-of-scope, so I don't give this much hope. would be kinda neat tho.

**Comment by OxygenCobalt** [comment]
I've rejected this before and will reject it again, for two reasons:
1. Most of my music is instrumental, so I gain no benefit from lyrics. When it does have lyrics, I tend to memorize them through enough listens.
2. I cannot get LRC files with scoped storage limitations. They are not exposed anywhere. I could only support embedded lyrics, which are nowhere near as useful.
3. I have only seen music apps get *buggier* when they add lyrics, due to issues with the playback position, how lyrics have to be crammed into the playback UI, and so, so many state issues. I want to add useful things that won't horribly break the app in the process.
