### ISSUE TITLE
add Motion Transitions

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#191]
#### Describe the feature you want to implement:
add motion transitions when clicking an item in albums, artists or Genres and it transitions to the details screen.
similar to the example here:
https://youtube.com/clip/UgkxeHo_q9GdYWcZ6hnwU919-Xym7k_WJnAN

#### Is your feature request related to a problem? Please describe:
not really, would be neat tho

#### Do other music players handle this? If so, how?
oto music implements this

#### Why do you think this will improve everyone's usage of Auxio?
monkey see cool transition => neuron activation

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
I really wish I could do this, but at the moment, I can't for two reasons:

1. I cannot get them to work. I have no idea why except that my app does not have the arbitrary magic that other apps do, so I'm not blessed with the ability to leverage motion transitions.
2. They are filled with bugs. Motion transitions are "one and done" transitions, which results in visual issues. You can easily reproduce this by downloading Retro and scrolling as soon as you open up an album/artist/genre. The image will not move with the scrolling, as it *can't* with how it's structured. This is such a basic issue that iOS solved in 2014, but google devs close any issue bringing it up with "sorry its just like that because reasons".
    - A theoretical mitigation would be for me to disable scrolling until the transition is done, but that is really bad for UX and I have no idea how to do that.

As a good rule of thumb, I do not like adding eye candy to Auxio. Not that I necessarily hate it, I just know that eye candy on Android is a buggy no-good mess that always breaks down outside of their tech demos. I will take boring fade transitions over broken motion transitions any day.

**Comment by OxygenCobalt** [comment]
Okay, so I think I've found a bit of a nicer compromise. I can implement a shared axis transition in the app, which is sort of semantically similar and looks kinda nice, but is also ***far*** less of a buggy mess:

https://user-images.githubusercontent.com/65370175/181152794-b1b8c7d3-22cc-4ad9-892f-c857879702f8.mp4

Maybe later I'll implement motion transitions as an option for those who want the dumb eye candy

**Comment by KraXen72** [comment]
sure this is good 👍
