### ISSUE TITLE
setup automated F-Droid update check

### ISSUE THREAD

**Issue by foss-** [OxygenCobalt/Auxio#192]
**Currently**

Auxio is listed under https://monitor.f-droid.org/builds/noupdatecheck
> These have Update Check Mode set to None, so we can't automatically know when new versions are available. We need to implement new methods of checking, and check manually in the meantime. Apps which likely won't ever be updated, or for which the author would let us know personally, don't appear here.

**Expected**

To reduce overhead for releases by applying some automation and have new versions appear in F-Droid sooner, it would be nice to have this changed.

Additional context: PR to re-add Auxio to main F-Droid repo: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9307 as discussed in https://github.com/OxygenCobalt/Auxio/issues/21#issuecomment-868689427

**Comment by OxygenCobalt** [comment]
I can't do this due to how I use ExoPlayer. 

Auxio relies on an ExoPlayer extension enabling FLAC playback before Android Oreo, which thus requires some kind of pre-build script that compiles the extension. Such a script must be within the F-Droid build recipe, and should be kept in lock-step with the ExoPlayer version. If I were to enable auto-update, the ExoPlayer version in the extension would drift from the version used in the app. Thus, I must update manually.

This could be remedied if I was allowed to use my [in-repository pre-build script](https://github.com/OxygenCobalt/Auxio/blob/dev/prebuild.py), as that is kept in lock-step with the ExoPlayer version without me having to update the build recipe, but the F-Droid maintainers would never allow it, as that is functionally arbitrary code that I could change at any time to say, `rm -rf / --no-preserve-root` their build server.

Alternatively, I could set up another means of distribution a la NewPipe, but I don't have the hardware to set up my own server like that.

**Comment by foss-** [comment]
Thanks for explaining.

**Comment by OxygenCobalt** [comment]
I usually have a grace period of a 3-4 days to make sure I didn't just ship a catastrophic bug or regression. I know there are enough people that directly download Auxio releases from GitHub that, if a massive bug was encountered, they would report it. Then, it's a day or so to get the updated build script merged into the f-droid repository, and then anywhere from 1-2 weeks to have F-Droid recognize, build, and update the app. I really don't know why the last step is so slow.

**Comment by OxygenCobalt** [comment]
Update: With enough wrangling with gradle config and submodules, I've managed to remove dependency on the prebuild.py script. This should make auto-update possible in the next version.
