### ISSUE TITLE
Smart rescanning

### ISSUE THREAD

**Issue by nift4** [OxygenCobalt/Auxio#197]
#### Describe the feature you want to implement:

In 2.5.0, automatic scanning was added. It apparently brought a lot of internal issues out of the way. However, I have a few suggestions that would improve the experience in my opinion.
- Rescan when bluetooth gets enabled
- Run rescan service only when playing audio

#### Is your feature request related to a problem? Please describe:
A foreground service that eats battery seems very much overkill to me.

#### Do other music players handle this? If so, how?
VLC does rescan the library when you enable bluetooth.

#### Why do you think this will improve everyone's usage of Auxio?
An foreground service eats a lot more battery than this, which however covers most cases of the user wanting to play a (new) song.

#### Due Diligence:
- [X] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [X] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [X] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
> Rescan when bluetooth gets enabled

What is the reasoning behind this? Nothing about enabling bluetooth should change the music library.

> Run rescan service only when playing audio

Doing this would make the app state incoherent. What if one edits their music library when playback is not ongoing? Since the music library is global and no other piece of code is capable of updating it, the wrong items will show up in the music library, defeating the purpose of automatic rescanning. I need some piece of code consistently running in the background to have reliable automatic rescanning, which due to restrictions in later android versions means I must use a foreground service.

**Comment by nift4** [comment]
> What is the reasoning behind this? Nothing about enabling bluetooth should change the music library.

VLC speculates that the user wants to connect their bluetooth earphones.

> What if one edits their music library when playback is not ongoing?
One could simplify what I meant as "if Auxio is running, make sure the foreground service runs, and stop it if auxio gets closed"

**Comment by OxygenCobalt** [comment]
> VLC speculates that the user wants to connect their bluetooth earphones.

That's kind of dumb, honestly.

> One could simplify what I meant as "if Auxio is running, make sure the foreground service runs, and stop it if auxio gets closed"
