### ISSUE TITLE
Add a shortcut to access the system's equalizer

### ISSUE THREAD

**Issue by mariobrostech** [OxygenCobalt/Auxio#203]
#### Describe the feature you want to implement:

I'd like for there to be a shortcut to the Android system's equalizer that Auxio can make available in the app's settings or through the menu options that are present whilst playing a song.

#### Is your feature request related to a problem? Please describe:
Yes. Not all Android ROMs provide easy access to the system's built-in equalizer. While Samsung provides the option in the device's sound settings, AOSP doesn't provide the same option. And, even in cases where the option is provided natively, it's often buried in several menus. Making the option to open the system EQ through Auxio would make them easier to adjust.

#### Do other music players handle this? If so, how?
Yes, other apps handle this functionality. As noted above, many apps will put this option in their settings or in a menu option that's visible in the media player. An example of this is in ViMusic, where an option to open the system's equalizer can be found in the player and app settings.

#### Why do you think this will improve everyone's usage of Auxio?
Adding this feature will add visibility to the system's native equalizer, which will make it both possible and quick for users to adjust equalizer options with very little work needed for the actual implementation since the equalizer is handled by the system.

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Don't some OEMs not provide the system equalizer? If I were to implement this, I would probably get a bunch of issues of "Why isnt the equalizer not working" because their Huawei device just does not have one. If I were to implement an equalizer, it would almost certainly be an in-house implementation as that would work consistently on all devices (and possibly with far more functionality compared to the system equalizer).

**Comment by mariobrostech** [comment]
You are correct; not all OEMs provide a system equalizer, but they really should, given that AOSP itself has one. Besides, if a ROM doesn't have a built-in equalizer, the system will show a toast notification saying something along the lines of "No equalizer app installed." Because of this wording, I assume that someone could install a third-party app that could replace this functionality if needed.

I don't develop Android apps, but my understanding is that there's no additional work changes you'd need to make besides linking to the system equalizer if you wanted to use it. The equalizer applies to all audio streams besides calls and doesn't appear to require custom changes from the app developer. Though, I could be wrong.

You also mentioned the possibility of implementing your own equalizer. This would obviously be the preferred solution, but I opened this issue since you had rejected a similar issue where someone proposed that you do this, and you stated that it wasn't a priority for your usage, so do you decided to dismiss it. Has your standpoint on this changed since?

The reason I opened this issue is because implementing the system equalizer seems like it would be much less work while still retaining functionality on most devices that ship with one. And, for those that don't, then would be no different than just not having the feature to begin with.

**Comment by OxygenCobalt** [comment]
> I don't develop Android apps, but my understanding is that there's no additional work changes you'd need to make besides linking to the system equalizer if you wanted to use it. The equalizer applies to all audio streams besides calls and doesn't appear to require custom changes from the app developer. Though, I could be wrong.

I've looked at other app's equalizer implementation, and I really dislike it. It's largely designed with the assumption that I'm using `MediaPlayer` (I am not), and leaves you at the whim of OEM quirks. Plus, comparing the system equalizer to the equalizer of something like poweramp, there seems to be a lot of functionality missing. It would be preferable to implement my own, and I definitely can with ExoPlayer.

> You also mentioned the possibility of implementing your own equalizer. This would obviously be the preferred solution, but I opened this issue since you had rejected a similar issue where someone proposed that you do this, and you stated that it wasn't a priority for your usage, so do you decided to dismiss it. Has your standpoint on this changed since?

My stance has changed a little since #113. Lots of my apprehension came from integrating an equalizer into the UI and the performance issues that might come with an internal implementation. These are starting to be ironed out though, so while it's not priority, it's also not something that I outright reject anymore. I'll file an issue when I do definitely set out implementing it though.

**Comment by mariobrostech** [comment]
Ok, thanks for the clarification! Hopefully, you can get it implemented sometime down the line 🙂
