### ISSUE TITLE
Scroll current item to the top in the queue list

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#210]
#### Describe the feature you want to implement:
currently, the queue opens with no scroll offset, and shows usually already played music. I'd like it if opening the queue when you open auxio from the bg/first time, it would come "pre-scrolled" (with some scroll offset) so the currently playing songs is in view.

#### Is your feature request related to a problem? Please describe:
when you have a long queue and want to edit a few of the next songs, you have to scroll all the way to what is currently playing. not a major issue but would improve QOL

#### Do other music players handle this? If so, how?
same as i suggested

#### Why do you think this will improve everyone's usage of Auxio?
see paragraph regarding issue

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [F AQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Not possible. RecyclerView will only scroll just enough so that the position I specify is visible, and no further. I can't just specify "Scroll to this position plus how many items you  can show" either, as that could lead to out-of-bounds region and result in no scrolling occurring.

**Comment by OxygenCobalt** [comment]
Actually, I think I can do this. If I override the "smooth scroller" implementation I can make the list settle the item at the top or middle instead of the bottom.

**Comment by OxygenCobalt** [comment]
Okay, I've managed to get this working. While the smooth scroller idea failed, it turns out I really could just tell the RecyclerView to "scroll to this item and a bit more" without issues by simply clamping it to the queue size.

Here's a little demo:

https://user-images.githubusercontent.com/65370175/210119595-8c1b4525-dbd3-421c-9fad-5a3024c0e3b7.mp4

There are a few little issues. Sometimes the queue will scroll *close* to the top and show a previous item. There's nothing I can do to fix this, and honestly the benefit outweighs the visual bugs.

What's super funny is that Youtube Music (The app I copied the queue system from) *doesn't* do this. Feels nice to 1-up Google, I guess.
