### ISSUE TITLE
Command buttons 

### ISSUE THREAD

**Issue by Atrafon** [OxygenCobalt/Auxio#215]
Buttons shows as commands.![Screenshot_20220812_102437_org.oxycblt.auxio.jpg](https://user-images.githubusercontent.com/106192957/184306283-53f4a721-d458-4b79-81e8-dc4f9f93bb7c.jpg)![Screenshot_20220812_102551_org.oxycblt.auxio.jpg](https://user-images.githubusercontent.com/106192957/184306306-785535d5-0abc-4408-8a0f-de2fef0a022f.jpg) 
My phone: Honor 8X, Android 10.Auxio version: 2.6.1.

**Comment by OxygenCobalt** [comment]
I need more context. Are you talking about the `@android:string/ok`? That seems to be a translation error since Weblate is terrible.

**Comment by Atrafon** [comment]
Yes, I was talking about @android:string/ok. And, yes, you were right about weblate.![Screenshot_20220812_231831_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/106192957/184438442-5c4cb528-7509-4d14-a71b-513c88f93178.jpg) ![Screenshot_20220812_231839_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/106192957/184438495-264acf97-78ca-426d-91a2-ffb1864f6792.jpg)

**Comment by OxygenCobalt** [comment]
Yeah, the idea is that "@android:string/cancel" should be ignored in favor of the note "Actual string: Cancel", and that should be translated. This is because the built-in "OK"/"Cancel" strings are in-complete, but I still want to leverage them if I don't have a translation. Turns out this is a terrible idea.
