### ISSUE TITLE
Queue bottom sheet should be rounded according to Round Mode setting

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#227]
#### Describe the feature you want to implement:
Queue bottom sheet should be rounded according to Round Mode setting

#### Is your feature request related to a problem? Please describe:
It feels inconsistent having the straight bottom sheet with rounded mode on.
sure, keep it for the sharp album covers
  
#### Do other music players handle this? If so, how?
-

#### Why do you think this will improve everyone's usage of Auxio?
see 2.

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
I really want to do this, but there's one issue: Visual clipping.

To get the UI of the app to move out of the way of the bottom sheet, I have to measure it. This means that the UI will not be drawn in the gaps between rounded corners, which becomes really infuriating once you notice it. I could fix this by instead padding the UI instead of measuring it, but this comes with so much insanity and poor API design that it's also equally unreasonable. Just rounding the queue sheet (which does not suffer from clipping) also does not sit right with me, as it's consistent.
