### ISSUE TITLE
Album is always played in alphabetical order

### ISSUE THREAD

**Issue by rusty-snake** [OxygenCobalt/Auxio#242]
#### Describe the bug/crash:

Album is always played in alphabetical order.

#### Expected behavior

Album is played in track order. As in VLC.

#### Steps To Reproduce the bug/crash:

Long press an album and tap play.

#### Phone Information:

Google Pixel 6, GrapheneOS (AOSP 13)

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
That shouldn't be happening. The play order is dependent on the current sort of the album view itself, but that can't be alphabetical unless a setting migration failed.

Can you change the sort to "Track" (Click on an album -> Click the three lines -> Select "Track") or does the app crash when you do that? If the latter occurs, you may need to clear storage since a migration probably failed.

**Comment by rusty-snake** [comment]
> Click on an album -> Click the three lines -> Select "Track")

This does not have any effect. Not even asc/desc works.

No crash BTW.

**Comment by OxygenCobalt** [comment]
That is completely inexplicable. I can't reproduce any behavior like this on my physical or emulated devices, so I'm starting to think GrapheneOS is trying to block the `SharedPreferences` API in some way. Can you change the sort *anywhere* in the app?

**Comment by rusty-snake** [comment]
Sorting of all Albums or genre works.

**Comment by OxygenCobalt** [comment]
I have no idea then. I can only assume this is device-specific android insanity that I can't fix on my end. Sometimes things like this just happen and I have no clue why.
