### ISSUE TITLE
Enable theme customization on Android 12+

### ISSUE THREAD

**Issue by rusty-snake** [OxygenCobalt/Auxio#243]
#### Describe the feature you want to implement:

Add an option to enable dark/light theme independent of OS setting.

#### Do other music players handle this? If so, how?

A lot of other apps provide a option to override theme to dark, light or system.

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
This setting is implemented below Android 12, but I don't see why it's needed from Android 12 onwards. My logic is that the picker is only useful if your OEM does not implement a global toggle and you must do it app-by-app, but that shouldn't really occur anymore beyond 12.

Is there any other benefit besides that other apps have it? I usually don't implement X because other apps do it.

**Comment by illdeletethis** [comment]
only having a system wide toggle is quite unpleasant, as some apps appear a lot nicer in the opposite theme, or can be much less usable in the chosen theme for everything else (sygic dark mode is awful for example, difficult to read maps in, which for a navigation app is a fatal flaw).
in that sense i am glad to not be on android 12

**Comment by OxygenCobalt** [comment]
Okay, that's reasonable.
