### ISSUE TITLE
Support Opus files with .opus extension in Android < 10

### ISSUE THREAD

**Issue by fice-t** [OxygenCobalt/Auxio#259]
#### Describe the feature you want to implement:

Opus files with an extension of `.opus` (which is the [official](https://wiki.xiph.org/MIME_Types_and_File_Extensions#.opus_-_audio.2Fogg) extension) should be indexed and treated like other valid audio files in all supported Android versions.
#### Is your feature request related to a problem? Please describe:

The problem is a library with many `*.opus` tracks will have many tracks that appear missing when on Android < 10.
#### Do other music players handle this? If so, how?

[Vanilla Music](https://github.com/vanilla-music/vanilla) (only other Android player I have experience with) has an option [`Scan full filesystem`](https://github.com/vanilla-music/vanilla/blob/27cd3ea0c1cf59ce55068b6fcea080083554d7e9/app/src/main/java/ch/blinkenlights/android/medialibrary/MediaScanner.java#L135) for its media scanner that upon finishing results in .opus files working as expected.

#### Why do you think this will improve everyone's usage of Auxio?

Opus files in the standard and common `.opus` extension work and Android versions prior to 10 ([which is when they finally fixed the issue](https://cs.android.com/android/_/android/platform/libcore/+/d5e73ac1a2c92dd929e1462b63d6e36509813486)).

There are many people stuck on older Android devices and it would be nice to not have to mass-rename media files for the player to recognize the files.

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
The lack of support from opus is derived from an issue in the system media database, which Auxio relies on. Since this is a system API, I cannot work around it or patch it in any meaningful capacity. I cannot implement something like "Scan full filesystem" either, as it requires traversing the device filesystem which is no longer possible on modern android. 

Your only real option is to rename all .opus files to .ogg, something that I'd imagine should be quite easy to automate. If you want, I could try to create a bash command that automates such a task.

**Comment by OxygenCobalt** [comment]
Actually might be alleviated by #322, which should be a modern way I can grok directory information.
