### ISSUE TITLE
full-image grid album view

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#283]
#### Describe the feature you want to implement:
full-image grid album view
(later, when artist images are implemeted, also full-image artist view)
the key is no/ultrathin spacing between albums, no border rounding and no title.
See AntennaPod subscription view:
![Screenshot_20221126-145802_AntennaPod.png](https://user-images.githubusercontent.com/21956756/204092644-a25a0ba7-dd00-4fc3-b616-335bc4e6ce69.png)
you might think it would be hard to know what album is what, but that's the joy - sometimes i forget i even had this album downloaded, and play it without maybe 100% knowing what it is.  
this would be an option in the display dropdown, not a setting in settings.

#### Is your feature request related to a problem? Please describe:
sometimes, i do not know which albums to listen to. it w

#### Do other music players handle this? If so, how?
Antenna pod, attached in screenshot.

#### Why do you think this will improve everyone's usage of Auxio?
see the first section

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
I've been largely hesitant to add other display styles due to the fear of scope creep. If I add a grid view, eventually I'll be expected to add different span-sizes, and then different item colorings, and then different image styles, etc. Eventually you are left with something like Retro Music where there are 10+ different item styles and none of them work very well. 

If I were to implement it, it would be a more unilateral setting that changes the appearance of *all* albums/artists/genres to be in a grid form. Currently this isn't really priority for me however.

**Comment by KraXen72** [comment]
understandable but still sad. if not clear enough, i don't care about any settings for this, not if there are 3/4/5 albums per row, it would be locked to 3 as you see in the image. no corner badges either.
just a nice view where you can see all your albums as if you've owned their physical discs/vinyls and laid them out on the floor.
and it does not need to be universal, it only makes sense for albums (as in vinyls) or then theoretically for artists. i can't think of why would anyone want to use it for anything else, like genres or songs (does not make sense)
