### ISSUE TITLE
Hope There is Syncing Lyrics:)

### ISSUE THREAD

**Issue by SaltyBill** [OxygenCobalt/Auxio#296]
I made my own syncing lyrics and it'll be cool if Auxio can read the files:)

**Comment by OxygenCobalt** [comment]
Duplicate of #286 and countless others.

1. Most of my music is instrumental, so I gain no benefit from lyrics. When it does have lyrics, I tend to memorize them through enough listens.
2. Most lyrics are LRC files, which I cannot obtain on modern android due to "scoped storage" limitations. This would restrict users to the less intuitive `SYLT` for MPEG files and some made-up format for Vorbis or FLAC, which I doubt would be sensible. Fetching them externally is also a non-option, as I have made a promise for Auxio to not have internet access.
3. I have only seen music apps get buggier when they add lyrics.
