### ISSUE TITLE
ID3v2 multi-value tags encoded with UTF-16 are mangled

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#302]
### Describe the Bug/Crash

see screenshot:
![Screenshot_20221230-194632_Auxio](https://user-images.githubusercontent.com/21956756/210103195-32c9e82f-fda6-47a9-8ee1-7f36a1c727e8.png)
![Screenshot_20221230-194645_Auxio](https://user-images.githubusercontent.com/21956756/210103200-34f8647c-a689-44ad-8798-8185724a1825.png)

i think it's something to do with encoding
in an app like automatag, the genre is correct
![Screenshot_20221230-194923_AutomaTag](https://user-images.githubusercontent.com/21956756/210103360-b64cd8bf-ad2e-46a4-b82c-4e8084fb7b68.png)

### Describe the intended behavior

read genre correctly

### What android version do you use?

Android 12

### What device model do you use?

Samsung Galaxy M21 (OneUI 4.1)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Agh, I thought I was done with encoding insanity. Care to send a test file?

**Comment by KraXen72** [comment]
ill send them on email, it wont let me upload here

**Comment by OxygenCobalt** [comment]
Okay. I'm waiting on your e-mail.

**Comment by OxygenCobalt** [comment]
If I were to guess at what is happening. The new ID3v2 text value parser has a bug in it. If that's the case, I'll have to do some nightmarish re-basing in my fork.

**Comment by KraXen72** [comment]
it also does it for artists lol
![Screenshot_20221231-165845_Auxio.png](https://user-images.githubusercontent.com/21956756/210149119-0cb39dd7-2813-43ba-8d65-7ba838a08b99.png)
![Screenshot_20221231-170244_Auxio.png](https://user-images.githubusercontent.com/21956756/210149124-1667410c-eeb8-4245-a711-e16c1e473f5b.png)

**Comment by OxygenCobalt** [comment]
AAAAAAAAAAAAAA. I still am trying to figure out what's causing this. All I can do is use trial and error.

**Comment by OxygenCobalt** [comment]
Figured it out.

Your tags are encoded in UTF-16. One important thing about this format is the fact that it has a "BOM" (Byte Order Mark) that signifies whether it is "big endian" (ex. "0x0 E" -> E) or "little endian" (ex. "E 0x0" -> E). The issue comes in that to save space with multi-value tags, taggers seemingly write the BOM to the first value, and then avoid writing it to all following values.

*I did not know about this.* When I added ID3v2 multi-value support to ExoPlayer, I thought that the decoded string would always contain a BOM when decoded with UTF-16. Since it does not, the String decoder then defaults to assuming that the String is *big-endian* UTF-16, and thus mangles all but the first value in a multi-value tag.

I'll work on fixing this. As for an interim measure, you can use a tagger to change the encoding to UTF-8, which does not use a BOM and won't have this issue.

**Comment by KraXen72** [comment]
oh, really interesting. thanks for the technical explanation. i might but i have a lot of songs and don't wanna re-tag them all currently.

**Comment by OxygenCobalt** [comment]
Yeah. The [latest CI artifact](https://github.com/OxygenCobalt/Auxio/actions/runs/3813278865) should have this issue resolved. Feel free to try it out and tell me if it fully resolves the issue. If not, send me the afflicted sample files, and the previous ones you've given me should work now.

**Comment by KraXen72** [comment]
it has been resolved. the debug apk is quite laggy but i assume that's just because I haven't filtered my folders (im loading like 2x more files) and also it's a debug apk

**Comment by OxygenCobalt** [comment]
Okay, great. I'll close the issue.
