### ISSUE TITLE
Settings categories

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#323]
Continuation of #318. Auxio has accrued a lot of configuration, so it makes sense to start using categories and sub-screens rather than a big list.

**Comment by NeeRaj-2401** [comment]
exactly, i was about to open an issue for this, thanx :)

**Comment by etyarews** [comment]
It really depends on what you want to do, there are 2 primary ways of organization:

1. Put everything into categories, and the main page has no actual thing to change (like Android Settings, or Gboard)
2. Add some options to the main page, but keep the bulk of it into sub-categories.

Considering Auxio doesn't have that many options, I would go for option #2. And I would also move "Music folders"  out of Content and put it on the main page, as this is basically the most important option on settings,

**Comment by etyarews** [comment]
The Drop-down option doesn't work in this case, as it is the same as opening a new page. 

A drop-down should be used in contexts where opening a new page is not suited, or where the "parent" information is relevant to keep on the screen.

**Comment by OxygenCobalt** [comment]
I'm sorry about this, but I don't think I'll actually be doing this any time soon. I can't really figure out a way to divide everything up that wouldn't result in really disjoint navigation. Auxio simply does not have enough distinct preferences for me to implement this.

**Comment by etyarews** [comment]
Fine, I will do it myself. 

* Music Folders is on the main page because it is important for the basic functionality of the app and the most likely to be changed immediately.
* Appearance Page:
* * Theme Divider:
Theme
Color Scheme
Black theme
* * Display Divider:
Library Tabs
Hide collaborators
Round mode
* * Notification Divider:
Custom playback bar action
Custom Notification action
* Behavior and Content
* * Behavior Divider
When playing from the library
When playing from item details
Remember shuffle
Rewind before skipping back
Pause on repeat
Save playback state
Clear playback state
Restore playback state 
* * Content Divider
Refresh music
Rescan music
Automatic reloading
Album covers
Music Folders
Exclude non-music
Multi-value separators

Actually, you can just use one single subpage: Behaviour and Content, the rest could be on the main page anyway

**Comment by OxygenCobalt** [comment]
Why would I lump two very different settings categories into the same sub-page?

**Comment by etyarews** [comment]
Behavior and Content are more or less "Advanced" options, so they are lumped together, but you could just make them separated pages.

I think Music Folders and settings related to the appearance are more likely to be used by average users, and most of them are things that the users can reasonably guess are options, almost all apps have theme options. The Rest of them (Behavior and Content) are more... "weird", are options that are not very common to other music players.

**Comment by OxygenCobalt** [comment]
Okay, I took your suggestions and was able to successfully implement the categories. Here's a demo:


https://user-images.githubusercontent.com/65370175/212778796-c73fce2f-ea26-45fd-823c-0899b3eb5ba1.mp4
