### ISSUE TITLE
Built-in tag editor

### ISSUE THREAD

**Issue by arijit4** [OxygenCobalt/Auxio#326]
### Description

Edit the tags of a music (for example `lyrics`, `artist`...) in the app it self.

### Problem solved

Song when downloaded gets the name as the musics named in the website I download from which we need to change. Again, `artist` tag most often is also set wrong.

This feature will help us to fix them from the app itself.

### Other implementations

`Retro music` already does this.

### Benefit

Song when downloaded gets the name as the musics named in the website I download from which we need to change. Again, `artist` tag most often is also set wrong.

This feature will help us to fix them from the app itself.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by KraXen72** [comment]
you can use musicolet app or automaTag tag editor. also, if you download from youtube, you can try using my project [tiger](https://github.com/KraXen72/tiger), it can produce nicely tagged songs from youtube/youtube music links.

**Comment by OxygenCobalt** [comment]
Programs should do one thing and one thing well. Music players and tag editors, while adjacent in use, are completely different in design. If I were to add it, it would result in a sub-par tag editor and a sub-par music player that would both be exceedingly difficult to maintain. Retro Music is actually unmaintained for this exact reason.

Use Automatag.

**Comment by alphanerdgen** [comment]
@OxygenCobalt It's funny that when I had a feature-rich music player installed on my phone, I wasn't listening to music all that much. But after installing Auxio, I've been listening to music much more now. 

It turns out I didn't really need large tiles, lyrics, tag editor, android auto, and a bazillion other features. I just wanted a simple music player that'd play music without any fuss (read bugs). And Auxio does that very well while looking beautiful at the same time. What more can I ask for?

Therefore, I sincerely hope that Auxio continues to remain "a simple, rational music player". I love this app! Thank you very much for creating Auxio.
