### ISSUE TITLE
The same album is in the same place.

### ISSUE THREAD

**Issue by Benjamin-Watson0** [OxygenCobalt/Auxio#345]
### Description

I noticed that the songs of the same album were not merged. Is this the original design? I guess it would be better if the songs of the same album were in the same position. Just like a folder.
![Screenshot_20230202_083632](https://user-images.githubusercontent.com/112467275/216202439-f7448f4f-917a-462d-90d0-f396c1a56969.jpg)

### Other implementations

Songs from the same album are in the same location.

![Screenshot_20230202_084130](https://user-images.githubusercontent.com/112467275/216202557-8dffb440-d5da-4548-bb69-c54b5fc3e582.jpg)

### Benefit

I'm sure it's very important and it will be more convenient.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I think you are incorrectly using the "Album Artist" tag for the songs in "Classic", and Auxio is working as intended. The "Album Artist" tag allows an album composed of a variety of different collaborators to be primarily credited to one collaborator.

Alongside this, Auxio also groups albums by their *name*, but also *artist values*. This is to prevent albums with the same name but made by different artists from being treated the same. 

In the case of "Classic", you are either:
- Not using the "Album Artist" tag, resulting in Auxio falling back to the artist tag. Since this artist tag differs between each song, Auxio assumes they all belong to different albums.
 - Incorrectly using the "Album Artist" tag, setting it to the same value as the "Artist" tag, and resulting in the same grouping problem.

I'd assume that part of your logic stems from thinking that Auxio will treat a folder of music like an album, but that is not the case at all. Auxio is explicitly designed for well-tagged libraries.

**Comment by Benjamin-Watson0** [comment]
Yes, the song does not use the "Album Artist" tag, but does the song have the "album" tag, and can't it be recognized?

**Comment by Benjamin-Watson0** [comment]
I thought for a while. What you said is very reasonable. The player I met before did not consider the issue of the album with the same name. I have never thought about this problem, because I have never encountered two albums with the same name, but there is such a situation.
You're right. It's more professional to identify albums.
Can we add a function called only identifying "album" tag as album categories? Like the rounded design of album pictures? At least I don't have two albums with the same name from me, and I have many songs. It would be too troublesome to add the artist name "album artist" tag to them step by step.
Thank you for your patience.

**Comment by Benjamin-Watson0** [comment]
What's your opinion? Do you think this is reasonable? I fully respect your opinion.

**Comment by OxygenCobalt** [comment]
Such an option has too narrow of a purpose to see myself implementing. You also do not need to edit your music one-by-one, as desktop tag editors like [kid3](https://kid3.kde.org) are able to mass-edit music files.

**Comment by Benjamin-Watson0** [comment]
OK, I understand.
