### ISSUE TITLE
Don't assume album as folder when album missing

### ISSUE THREAD

**Issue by occasionallyword** [OxygenCobalt/Auxio#356]
### Description

I would like for Auxio to not automatically assign an Album to songs when no album is given in the metadata.  I would like a setting for this behavior, instead of assuming it intentionally.  

Currently, some of my library has Title and Artist metadata, but lacks Album metadata.  Auxio will automatically display the Album as the name of the folder which my music is stored in on the, "Now Playing" screen.  I understand that some people store music and separate albums by folders, but this functionality should probably be a setting inside of Auxio.  

### Other implementations

In my experience, other players will either provide a setting for this behavior instead of assuming it, or will only display Album data when present within the tags of the individual song.  

### Benefit

This will benefit everyone's usage of Auxio by not providing an incorrect tag when no tag is present in the file.  A setting to determine this behavior makes logical sense, and would satisfy the needs of people who group things by folders/directories as well as by tags themselves.  

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is not under my control, and is actually from the media database automatically assigning the folder name to music. I also can't do my own filtering, as that will lead to collisions. For example, if an album has the name "0", is it because it's from audio files in `/storage/emulated/0`, or is it because the songs are from [Low Roar's Album "0"](https://musicbrainz.org/release-group/0745b812-4e4a-458e-a0b6-1bdb8b52a5bf)?

#322 should allow me to turn this behavior into a toggle. However, I'm not sure how to handle the fallback album case. Either:
- All songs without an album name are grouped into "Unknown Album" instances. This is easy to do.
- All songs without an album name just don't have an album *at all*. This is a thing I can do, but it also breaks one of the core invariants of Auxio's music model and requires a bunch more work.

**Comment by occasionallyword** [comment]
I understand, thanks for the explanation.  

It's not a massive problem for me, just a minor annoyance sometimes with how album art is treated from #342 mostly.

**Comment by OxygenCobalt** [comment]
Ah, okay. Definitely something I could see doing though, so I'll keep this open.

**Comment by OxygenCobalt** [comment]
#585 requested an additional option to interpret songs without an album as a single. This is possible, given that this is already configuration-controlled.

**Comment by OxygenCobalt** [comment]
This is no longer the case. The default is now "Unknown album". Will probably add the setting at a later point as desired.
