### ISSUE TITLE
Scan hidden music files

### ISSUE THREAD

**Issue by john4634** [OxygenCobalt/Auxio#364]
### Description

![Screenshot_20230219-105758_Markup](https://user-images.githubusercontent.com/125783926/219926252-afb3924b-5e5c-4159-8d99-9ce82bdcfbc9.png)
Some folders contains cover art image file. So folder is named as ".music" to avoid image showing in gallery.
But these folders are not recognised. Please add a feature to recognise these folders if we 'include' these folders.

### Other implementations

Other music player like poweramp recognise these type of folder and .nomedia files. 
![Screenshot_20230219-110535_Poweramp](https://user-images.githubusercontent.com/125783926/219928136-057ddeb4-4a99-4f8a-b25c-96dd9dd0192b.png)

### Benefit

This will avoid filling gallery with cover art image.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by e-zk** [comment]
Fairly certain the android media provider specifically ignores `.nomedia` and hidden files by design.   
I'm not sure if Auxio would be able to avoid this, and even if it could, I don't think this is desirable for many people. `.nomedia` in particular is _supposed_ to not be seen by the media provider - that's its whole purpose. 

What I do to avoid having the cover art fill my gallery is rename my covers to `.cover.jpg` (don't know if that still works) - they show fine in Auxio but my gallery app cant see them.

Further, in my gallery app I can exclude the `/Music` directory entirely so none of them show up.

**Comment by OxygenCobalt** [comment]
What @e-zk. This will be resolved however as soon as I can do #322, which is also what poweramp does.

**Comment by e-zk** [comment]
I was just thinking it may be possible to use the existing include/exclude directory feature? Say, if @john4634, added /.Music to the included directories.

**Comment by OxygenCobalt** [comment]
The media database does not scan hidden directories in the first place. "Including" a directory is more like filtering out everything in the media database but that directory, not adding the directory to the media database. Terrible naming, I know, but "Blacklist" and "Whitelist" are divisive to some and I really want to avoid a debate over it.

**Comment by OxygenCobalt** [comment]
This should be functionally done now that #322 is implemented @e-zk @john4634
