### ISSUE TITLE
Parent playing indicator does not correctly update in some situations

### ISSUE THREAD

**Issue by skj-skj** [OxygenCobalt/Auxio#380]
### Describe the Bug/Crash

1. Go to Album Tab
1. Play any Album
1. Add another Album to the Queue
1. When first song of the another play, see the music bar animation will be still on previous Album

### Describe the intended behavior

Music Bar Animation should move to Album whose song is been played.

### What android version do you use?

Android 12

### What device model do you use?

OPPO CPH2473

### Relevant log output

```shell
NA
The app hasn't crashed.
```

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Known issue related to #350. Will need to figure out how best to resolve it.

**Comment by OxygenCobalt** [comment]
Wait. I was thinking of a completely different issue due to the poor wording. I knew about a prior issue where if you did something like enqueue a song, then enqueue the album from that song, it would result in an incorrect playing indicator *in the queue*. Issue reported here is completely different, moreso just an edge-case rather than a #350 problem.
