### ISSUE TITLE
Loading your music library… showing on every open

### ISSUE THREAD

**Issue by foss-** [OxygenCobalt/Auxio#385]
### Describe the Bug/Crash

Auxio 3.0.3

When opening Auxio music library shows loading progress. I thought, that after initial loading, this would only show on library changes, but it happens on very load of auxio after fully closing the app.

### Describe the intended behavior

Reload library only on detected changes.
Probably related: https://github.com/OxygenCobalt/Auxio/issues/384

### What android version do you use?

Android 13

### What device model do you use?

PixelOS 13 2023-02-21

### Relevant log output

```shell
N/A
```

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Auxio loads the music library in-memory, which then means that after the app is fully closed, the music library is lost and must be reloaded on the next start. This is theoretically resolvable with the "full cache" I outlined in #207, but then I run into more problems since cache invalidation is hard. Not really keen on doing anything about it right now.
