### ISSUE TITLE
Media notification widget is broken

### ISSUE THREAD

**Issue by zsrv** [OxygenCobalt/Auxio#397]
### Describe the Bug/Crash

I'm not sure how to reproduce this. Many times, the media player widget for Auxio will have all white text except for the artist name (in light gray) and the play/pause button (in black, with no circle around it) on a white background, with no other controls visible (I figure they're white since I can still use them if I know exactly where they are/where to press).

I managed to force the text and controls to turn black by toggling the dark theme off (which is set to automatically toggle at sunrise/sunset) and then on again in the system display settings. I think I also closed the app then opened it again, then checked the widget in my notifications screen.

### Describe the intended behavior

I should always be able to read all of the text and see all of the controls in the media player widget.

### What android version do you use?

Android 13

### What device model do you use?

Google Pixel 6a, GrapheneOS

### Bug report

-

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I cannot reproduce this on my device. I need a screenshot of the visual problem to figure out what's going on. The app launcher tries to cache a lot of widget information, so I would guess that the scheduled theme change causes cache invalidation issues that causes the widget to get stuck somewhere between the dark and light theme.

**Comment by zsrv** [comment]
I've attached a screenshot. I just noticed that the text and controls that I thought were white are actually still visible, but a are in a very light color.

![auxio_media_player_widget_colors](https://user-images.githubusercontent.com/95176387/226992079-13b9daf9-945d-40c3-9165-3f9da774fe47.png)

**Comment by OxygenCobalt** [comment]
Oh, I was thinking of Auxio's widget and not the media notification. In this case, I'm unsure if the issue is in your album cover art (or the way auxio loads it), or if the system is breaking it. Can you turn off album covers by going to Settings -> Album covers -> Off, and then see if anything changes? Make sure to skip back and forth so that it fully updates.

**Comment by zsrv** [comment]
Thanks, wasn't aware this was actually a notification!

I turned album covers off at Settings -> Content -> Album covers -> Off, changed songs a few times, closed the media notification and let it reopen after changing songs. The media notification stayed the same through this.

I then opened the system Settings app > Apps > Auxio > Force Stop, reopened Auxio and started playing a song. After doing this, the media notification looks correct again:

![auxio_media_notification_correct](https://user-images.githubusercontent.com/95176387/226996190-a352b48f-b5d8-47fa-8d44-88e045022029.png)

**Comment by OxygenCobalt** [comment]
Huh. Do your songs not have album covers?

**Comment by zsrv** [comment]
Nope, these are FLACs with no embedded album art.

**Comment by OxygenCobalt** [comment]
Okay. In that case, the system falls back to some default Material You accents rather than using the album art colors. In this case, when your theme changes, the colors in the notification are only partially updated for some reason. I can't reproduce this on my device. This is only fixed when Auxio starts a new notification, as the correctly updated accents are accessed. SystemUI has the tendency to break in weird ways like this. Likely nothing I can do about it.
