### ISSUE TITLE
Save playback state more often

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#404]
Save the current playback state much more often, basically after any kind of update. I tend to listen to have Auxio open for a very long time, and that prevents the state from being saved, as the foreground state never ends. As a result, if I reboot my device, I lose my current playback state. If the saving occurred after each update, this would be resolved. 

Of course, this would be rate-limited such that it only saves maybe a minute or so after the change. This would also likely result in the playback state options being removed and replaced with a simple toggle for the functionality (Like in #107, #252).

**Comment by etyarews** [comment]
Oh, I think this is the issue I'm having. I use Tasker to start Auxio (albeit in a weird way because there's no static shortcut), when I plug my headphones, but also to stop (as in, stop the music, not stop Auxio) it when I remove them. 

Sometimes it results in Auxio forgetting I already listened to those tracks. Although I'm not quite sure what is going on cause Auxio doesn't appear to listen for the Stop signal. Even when it saves the play state, the music continues from where it was rather than the beginning of the song, which is what I think should happen? I know Auxio pauses the song automatically when the heaphones are removed, but Eleven, the LineageOS Music Player, also received the stop signal after it was paused.

**Comment by OxygenCobalt** [comment]
Auxio should save on a stop signal @etyarews, the issue is that the app is probably getting killed before it can finish saving, hence how it forgets those tracks. Again, this is what I want to fix with this change.

**Comment by etyarews** [comment]
I think the issue I described happen more when the screen is locked.

I've found a really weird behavior today where on playing it reverted to a very old playback state for some reason, which was weird as hell because it means it couldn't save for a very long time

**Comment by OxygenCobalt** [comment]
Okay, no *im* experiencing your issue @etyarews. Google Pixel patches introducing random behavior changes, ugh... I need to push this forward.

**Comment by etyarews** [comment]
The playback state was always kinda... awful on my end.

Please, at least save the state after each song starts, it would help alleviate some issues.

**Comment by OxygenCobalt** [comment]
> Please, at least save the state after each song starts, it would help alleviate some issues.

That's the idea. There would be some kind of rate-limiting such that it would save like 3 seconds after a song starts, so the app won't get overloaded if you start skipping radically.
