### ISSUE TITLE
Intelligent Sort Names, Take 2

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#423]
Going to leave this here as a list of things I still need to do regarding intelligent sort names.

1. Fix numerical comparison. Casting to an int leads to crashes, but the current solution simply pads integers out to a fixed size that will fail in certain cases. I need to create a more typical O(n) solution that compares an arbitrary amount of digits.
2. Combine the name normalization and punctuation removal of searching into the sort name. This is driven by 1 negating the ability for collation keys to be used.
3. Figure out exactly what should fall under "intelligent" sort names and what shouldn't. Easily the most difficult aspect here, as I have to balance internationalization concerns while also heavily delegating to user-specified sort information.

**Comment by enchainingrealm** [comment]
I was about to open an issue to provide some feedback regarding intelligent sorting, but I saw you opened this just now so I will leave a comment instead.

I use filenames to manage my music instead of tags. I use numbers in parentheses to indicate track order, e.g.
- (1) A Song
- (2) Another Song
- ...
- (10) The Tenth Song
- ...

Right now, intelligent sorting compares these names *lexicographically*, resulting in (10) counterintuitively being ordered before (2). It seems to me the most general fix (at a high level) is to tokenize each name character by character, but treat contiguous runs of digits as a single numerical token. For example, the first and tenth songs above would be tokenized into
- `["(", 1, ")", " ", "A", " ", ...]`
- `["(", 10, ")", " ", "T", "h", ...]`

Under this scheme, we compare names by comparing respective pairs of tokens, left to right, until a mismatch is detected.
- If we encounter a pair of numerical tokens, we compare them by magnitude
- If we encounter a pair of character tokens, we compare them lexicographically
- If we encounter a pair of one numerical token and one character token, we compare the first digit of the numerical token lexicographically with the character. The comparison must stop here, since this must be a mismatch.

This solution does not require padding each number to a hardcoded length, and can deal with numbers appearing anywhere in the names. This app is the best FOSS music player I have tried so far, and it would be great to get this implemented.

**Comment by OxygenCobalt** [comment]
That was my idea for a while @enchainingrealm, but I've actually decided against that due to it also having a precision limit past 2 billion. I'm currently trying to devise a runtime comparison algorithm that will compare integer components to arbitrary precision.

**Comment by enchainingrealm** [comment]
Are you referring to the maximum value for an `int` type, which is around 2 billion? To work around this, the numerical tokens can be stored as strings instead of `int`s. Then, we can check if a token is numerical by checking if its first character is a digit. We can compare numerical tokens by magnitude as follows:
- First, remove all leading zeros from the tokens. (We can do this virtually by incrementing pointers/indices.)
- Then, if the tokens have different lengths, the longer token is greater.
- Otherwise, compare respective characters (digits) from left to right, and stop upon mismatch.

This should work for all non-negative numerical tokens. The approach can be extended to incorporate leading positive/negative signs. Overall, I think the general approach to tokenization and comparison I described above should be orthogonal to the details of how tokens are represented.

**Comment by OxygenCobalt** [comment]
Yeah, that's effectively the algorithm I am looking to implement @enchainingrealm. I have certain concerns regarding memory. One of the things I am currently working towards is reducing the size of the in-memory music library, something I think in-memory tokenization would worsen.

**Comment by enchainingrealm** [comment]
Could tokenization be implemented in O(1) space using pointers and indices? After all, we don't actually need to store a list of tokens, because the comparison algorithm never reads any token twice. By interleaving the tokenization code and the comparison code, we can calculate the next tokens on-the-fly as required in the comparison process. This also produces some minor runtime benefits, because not all tokens need to be calculated if the comparison process returns early.

This is similar to the Python concept of generators. I am not familiar with Kotlin, so I don't know if this is a native Kotlin feature as well, but the overall idea of bookkeeping using pointers to avoid explicitly storing the token list should hold regardless.

**Comment by OxygenCobalt** [comment]
Yeah, that's the idea I was going for, assuming that no other portions of the app need that kind of in-memory token information to function.
