### ISSUE TITLE
Material Files incompatibility (?)

### ISSUE THREAD

**Issue by Nomagno** [OxygenCobalt/Auxio#430]
### Describe the Bug/Crash

1. Install Material Files
2. Install any other file manager (both the default AOSP one and Simple File Mamager worked for me)
3. ... Well, install Auxio duh
4. Set a folder whitelist in Auxio to a specific folder foo
5. Download music (I only tested with .opus file format)
6. Copy it to folder `foo` with Material Files
7. Rescan library with Auxio
8. No new music found
9. Rename the file inside `foo` with the other file manager to literally anything else than its current name while preserving the file extension
10. Rescan library with Auxio
11. Music found (!?)

### Describe the intended behavior

Well, it should be detected in all instances

### What android version do you use?

Android 11

### What device model do you use?

Xiaomi Redmi 9 (Plain AOSP flavour of phh-treble)

### Bug report

I'm sure what to add here

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Auxio is likely intentionally filtering out duplicate music entries. The android media database has a habit of duplicating song entries for no reason, and so Auxio will filter out songs with the same metadata. 

In your case, I'm assuming that you don't have any "Name" music tags and just use the file name instead. In this case, since your copied file has identical file names (among other identical information) to the pre-existing file, Auxio ignores it and only shows one song entry.

I'm not really sure why anyone would want to have duplicate song entries, so I don't plan on changing this behavior.
