### ISSUE TITLE
Consider making "Playing Now" screen use content colors rather than system

### ISSUE THREAD

**Issue by etyarews** [OxygenCobalt/Auxio#438]
### Description

Material Guidelines have a section related to [content based dynamic colors](https://m3.material.io/styles/color/dynamic-color/user-generated-color#8af550b9-a19e-4e9f-bb0a-7f611fed5d0f)

### Other implementations

The guidelines themselves use the example of using album art as the color source.

### Benefit

The playing now screen seems a good place to make use of the feature and add a splash of color for Auxio.

It might be used in the mini player as well.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by etyarews** [comment]
Alright, so to expand on this:

I think dynamic content color is awesome and, considering Material Design 3 concepts, severely underutilized. There's a reason the guidelines use album art as an example, because it looks awesome.

The issue is that making Auxio as a whole use it is a bit... Weird. There's too many places where album art is related to content. But the Playing Now screen is perfect for it as it is definitely a place where there's is a clear album art that is more important than the others

**Comment by OxygenCobalt** [comment]
I've largely rejected this in the past given how there is basically zero library support for creating something like this in a sensible way:
1.There is no standard library I can really use to implement something like this. You have [androidx palette](https://developer.android.com/jetpack/androidx/releases/palette), but that is for old Material Design. This is really common, as the material design teams and the android UI teams have terrible communication with each-other. There might be a few third-party toy projects that could be used, but I really don't want to rely on those since they are far less reliable.
2. Any kind of custom theming would have to be run-time based, infecting a ton of UI components and massively increasing the complexity of theming. It's the same reason why Auxio has a limited color scheme selection.

I agree that it's a little cool. But I have a really high bar for eye candy given how much it completely breaks down outside of tech demos. Sorry.

**Comment by etyarews** [comment]
Hmm, so if there's a library that takes care of it will you implement it?

Btw, I don't want to open another issue related to eye candy, have you looked at the recently released[carousel component](https://m3.material.io/components/carousel/) ?

It is comprised of Large, Medium and Small sizes. I'm thinking you could set it up to only use one visible large size as the album art in the now playing screen, and swiping left or right would change tracks with album art animating as a carousel. I think there was something similar in the Google I/O presentation

**Comment by OxygenCobalt** [comment]
> Hmm, so if there's a library that takes care of it will you implement it?

I would give it more thought. The second barrier is implementing a smooth transition between colors.

> Btw, I don't want to open another issue related to eye candy, have you looked at the recently released[carousel component](https://m3.material.io/components/carousel/) ?

I'm aware. I'm trying to track it in #94.
