### ISSUE TITLE
Play Next

### ISSUE THREAD

**Issue by biraj21** [OxygenCobalt/Auxio#44]
Option to play a song directly after current song.

**Comment by OxygenCobalt** [comment]
Unless I'm missing something, that option already exists under "Add to queue".

**Comment by biraj21** [comment]
Yeah, but suppose I added song 1 to queue and now I want song 2 to play
next instead, I can't do that because it will be added behind song 1.

**Comment by OxygenCobalt** [comment]
Hm. This doesn't benefit my usage, sorry.

**Comment by OxygenCobalt** [comment]
I'm re-opening this issue. This is because I recently figured out that pretty much *the rest of android* assumes that your app has a single queue. This acts as a major hold-up to a lot of features that people want, so I'm considering whether to switch Auxio to a traditional Play Next/Add to queue system after all.
