### ISSUE TITLE
"No music found" when loading from external SSD 

### ISSUE THREAD

**Issue by StarPepe** [OxygenCobalt/Auxio#455]
### Describe the Bug/Crash

When I try to load my music from an SSD under the "Music folders" setting and press "Include" for the selected folder, I am greeted with a "No music found"-error.

### Describe the intended behavior

I'm trying to play music from a folder on an external SSD formatted to exFAT, since my SD card is too small to hold my entire music library.

Is loading from an exFAT-formatted drive not supported? 
All of my audio files are in the .FLAC-format, too.

### What android version do you use?

Android 13

### What device model do you use?

I own a Fairphone 4 flashed with CalyxOS.

### Bug report

I can't provide a bug report, since I'm unsure whether this is a bug or simply an unsupported feature.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is likely because MediaStore is unable to index the SSD, I would recommend trying to [troubleshoot](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting#music-is-missing-from-the-library) to see if you can prod your phone into indexing the drive, but if that doesn't work there is really nothing I can do about it. Maybe #322 will work better when I work on it.
