### ISSUE TITLE
Removing last and active item in queue crashes app

### ISSUE THREAD

**Issue by min7-i** [OxygenCobalt/Auxio#464]
### Describe the Bug/Crash

1. Add one or more songs to the queue.
2. Play the last song in the queue.
3. In the queue, swipe to delete the last item.
4. The app crashes / force closes.

When there is only one item in the queue, the app doesn't force close, but the bottom player bar disappears and sometimes isn't shown again when playing a new song.

### Describe the intended behavior

I'm not sure what the best behavior would be.

When there are other items left in the queue it should stay open. So the user can further modify the queue and select another item from the queue to play.

When there is no other item in the queue it should probably just be closed.

### What android version do you use?

Android 13

### What device model do you use?

Google Pixel 6a

### Bug report

I don't have a bug report file.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Identified the issue, was caused by me not handling a case where the removed song was the current song at the end of a queue. In this case, the queue would be interpreted as entirely empty, but the app was still told to remove one song, resulting in the crash.

It also seems like there is another issue in how you can't play songs after you remove that last item from the queue. That's a problem with the playback UI that I've also fixed.

Thanks for reporting this.
