### ISSUE TITLE
New Album Artist Info includes features

### ISSUE THREAD

**Issue by nzure** [OxygenCobalt/Auxio#488]
### Describe the Bug/Crash

Since 3.1.2, Artists whose first album have a feature keep the feature in their name. This issue is reproducible with different artists.

E.g: My oldest Kygo Song has the Artist credit “Kygo feat. Ella Henderson”. Now, every mention of “Kygo” shows “Kygo feat Ella Henderson” instead (see screenshots). None of the albums / tracks in the pictures should have a Ella Henderson as a feature. This does not affect the feature itself, her tracks are displayed correctly.

Apart from not looking nice, this change kinda confuses music scrobblers, as the credits don’t really match anymore. Additionally, it would be nice to keep the artist credits as written in the tags and not just colon separated strings.

![Screenshot_20230624-125651](https://github.com/OxygenCobalt/Auxio/assets/68470934/d7aae970-6d7e-484e-9127-58a5a410d887)
![Screenshot_20230624-125708](https://github.com/OxygenCobalt/Auxio/assets/68470934/a5df5376-9606-4257-87ce-d3bcee4fbc11)
![Screenshot_20230624-125719](https://github.com/OxygenCobalt/Auxio/assets/68470934/9343c1f5-c6f7-44ab-9b27-2db6b7b5d2f1)

### Describe the intended behavior

The artist names should not include features.

### What android version do you use?

Android 13

### What device model do you use?

Google Pixel 5

### Bug report

-

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I'd need to see the tags of a sample file in something like [kid3](https://kid3.kde.org) @nzure. I'm pretty sure the issue here is that you have poorly formatted `ALBUM_ARTISTS` tags that Auxio is now able to pick up.

**Comment by nzure** [comment]
I believe that the tags are correct. It is a single with a feature, so the feature is included in the album artist variable.

Screenshot from Picard:
![Screenshot from 2023-06-24 17-01-31](https://github.com/OxygenCobalt/Auxio/assets/68470934/96f1bb0e-0c3f-4bc0-8a6a-c57b39b5843e)

**Comment by OxygenCobalt** [comment]
Okay, what's occuring here is something like:
1. In 3.1.1, the album of your first alphabetical song had "kygo" as an album artist, which Auxio used.
2. In 3.1.2, Auxio switched to picking the oldest album of an artist, which in this case had an album artist with a feature.
3. Since you use MusicBrainz IDs, Auxio didn't split the artist like it normally would with differing names (this is on purpose), so in the end the feature became the artist.

This is largely working as intended and is a consequence of poor tagging. I would highly recommend figuring out why Picard isn't writing `Album Artists` (it normally does that). Prioritizing `Artists` would be not work, as those are inconsistent across an album and would lead to even worse results.

**Comment by nzure** [comment]
Yeah, sorry for  bothering.

For anyone else wondering, you need to at this tagger script to picard: `$setmulti(albumartists,%_albumartists%)`
