### ISSUE TITLE
Duplicate empty artists

### ISSUE THREAD

**Issue by alessandrococco** [OxygenCobalt/Auxio#525]
### Describe the Bug/Crash

Hello,

I just noticed that Auxio creates an empty duplicate of all artists in my library:

![image](https://github.com/OxygenCobalt/Auxio/assets/2331798/c0de21b8-4953-4d15-b48b-ee3ea829adca) 

![image](https://github.com/OxygenCobalt/Auxio/assets/2331798/05871156-8d59-4476-b139-ba891640fedb) 

![image](https://github.com/OxygenCobalt/Auxio/assets/2331798/a51a3504-b8aa-436b-abef-80dad30a79f2)

Album tags example:

![image](https://github.com/OxygenCobalt/Auxio/assets/2331798/1d69f8a6-8455-4fd5-b929-9fe525f8e9d1)

### Describe the intended behavior

No duplicates

### What android version do you use?

Android 13

### What device model do you use?

POXO X3 NFC (Lineage OS)

### Bug report

I'm using a clean install of Auxio 3.1.4

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is likely caused by incorrect MusicBrainz ID (MBID) configuration. Specifically, your track artists have MBIDs, but your album artists do not. Auxio treats artists that have MBIDs and artists that don't as different, resulting in the duplication. This is something I've been wanting to improve eventually, but have no idea how I would put a dent into. I'd recommend either completely using MBIDs in your library via an auto-tagger like [beets](https://github.com/beetbox/beets), or completely removing the tags.

**Comment by alessandrococco** [comment]
You're right, I forgot the MB Album Artist ID tag. I just added it to all my files and the duplicate entries are gone. Thank you for the tip! :smile:
