### ISSUE TITLE
Playlist filter + Specific playlist

### ISSUE THREAD

**Issue by STVGecko** [OxygenCobalt/Auxio#531]
### Description

Hello,

To get started, I'd like to thank you for creating this application. I'd like to suggest a few adjustments to make this application even more practical.

First of all, could you add the possibility of filtering the music in the playlists in the same way as in the main menu?

(screenshots are in French)

<img src="https://github.com/OxygenCobalt/Auxio/assets/71868745/97d99414-069c-4423-bfc4-7e03bb8737cd" width=15% height=15%>
<img src="https://github.com/OxygenCobalt/Auxio/assets/71868745/33ff34bf-9c10-46bc-9cd7-4548a00e0166" width=15% height=15%>
<img src="https://github.com/OxygenCobalt/Auxio/assets/71868745/f2750d7f-bd89-40c6-b21a-eaa50b34fc63" width=15% height=15%>
<img src="https://github.com/OxygenCobalt/Auxio/assets/71868745/b4b2beb9-2db0-434d-bb88-bfc857d0d2c7" width=15% height=15%>

As a second step, I also suggest adding 3 lists by default to the playlists (or albums section): "recently added", "recently listened to" and "most listened to".

These three lists, which are the default in the Samsung Music application, are very practical.

(screenshots are in French)

<img src="https://github.com/OxygenCobalt/Auxio/assets/71868745/216421f6-84c0-4eac-be94-ddc6b00a6d9e" width=15% height=15%>
<img src="https://github.com/OxygenCobalt/Auxio/assets/71868745/73a4746e-e4ba-4291-9016-92dc1000fbff" width=15% height=15%>

I need these two additions in order to switch 100% to this application (I'm currently on Samsung Music).

Thanks for reading and good luck with the rest. All the best.

### Other implementations

As a second step, I also suggest adding 3 lists by default to the playlists (or albums section): "recently added", "recently listened to" and "most listened to".

These three lists, which are the default in the Samsung Music application, are very practical.

(screenshots are in French)

<img src="https://github.com/OxygenCobalt/Auxio/assets/71868745/216421f6-84c0-4eac-be94-ddc6b00a6d9e" width=15% height=15%>
<img src="https://github.com/OxygenCobalt/Auxio/assets/71868745/73a4746e-e4ba-4291-9016-92dc1000fbff" width=15% height=15%>

### Benefit

I think these implementations will be beneficial in terms of user experience.

personally, I need these two additions in order to switch 100% to this application (I'm currently on Samsung Music).

Thanks for reading and good luck with the rest. All the best.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
> First of all, could you add the possibility of filtering the music in the playlists in the same way as in the main menu?

I'm assuming you mean the sort button. This is already done (#446), and will arrive in the next version.

> As a second step, I also suggest adding 3 lists by default to the playlists (or albums section): "recently added", "recently listened to" and "most listened to".

I don't really get any use from these. I usually know what I've added to my library as of recently, and play counts/times have never appealed to me.

**Comment by STVGecko** [comment]
> > First of all, could you add the possibility of filtering the music in the playlists in the same way as in the main menu?
> 
> I'm assuming you mean the sort button. This is already done (#446), and will arrive in the next version.

Oh sorry, I've often looked at the various proposals but I hadn't seen it.
 
> > As a second step, I also suggest adding 3 lists by default to the playlists (or albums section): "recently added", "recently listened to" and "most listened to".
> 
> I don't really get any use from these. I usually know what I've added to my library as of recently, and play counts/times have never appealed to me. You can sort by date added though.

This is a feature I usually use

**Comment by OxygenCobalt** [comment]
> This is a feature I usually use

Yes, but I generally only add features that benefit everyone's use, which includes my own. I created Auxio because I disliked other music players that have haphazardly added far too many features at severe cost to the user experience. You can also read this on the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing) page.

These kinds of recommended playlists always frustrated me, since I never really used them and would accidentally click on them while trying to go to playlists I actually wanted to play. I really don't want to bring that frustration back. The only exception to this is something like a default "Favorites" playlist, since I'd want to use that.

In addition, the technical details behind these kinds of playlists are also complicated. You have to track play counts and listening times in a database, which then becomes bug-prone when handling music library changes. You also need to consider the complexity in how these playlists would interact with the rest of the app.

There would likely be an large amount of bugs stemming from such a system, which would then take away time from future features and maintenance. Additionally, since I would never use these playlists, I might not notice bugs that I accidentally introduce, causing them to just silently break after an update.

I get this probably isn't a satisfactory answer. Sorry.

**Comment by STVGecko** [comment]
There is no problem.  I had consulted the page Why Are These Features Missing?

This second feature is an optional request.

All the best.
