### ISSUE TITLE
automatic maximise preamp until clipping detected feature

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#549]
### Description

adjusts loudness of preamp for every song automstically

### Other implementations

.

### Benefit

quality loudness

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is impossible to do since the volume amplification that won't cause one sample to peak will cause a louder sample to peak, requiring some janky rolling average code that would probably make the audio sound awful. I also am not comfortable with providing an option that could feasibly cause hearing damage over long periods of time.
