### ISSUE TITLE
Smoothness issue with big library

### ISSUE THREAD

**Issue by Tom4tot** [OxygenCobalt/Auxio#579]
### Describe the Bug/Crash

Please check my video as it speaks for itself.
Basically:
- The Artist tab is always smooth
- The Genre tab is always stuttering (probably because of my big library, I have close to 20k songs, mostly in the .opus codec)
- Scrolling in queue is always smooth
- Dragging songs in queue is only smooth if the queue is small enough, otherwise it becomes extremely laggy
- I forgot to show it in the video, but the search function is fairly slow as well, and there's a noticeable delay when typing letters. 

### Describe the intended behavior

Auxio should be smooth in all situations (of course, I'm saying it would be the ideal intended behavior, not that you have to fix it immediately :D).

### What android version do you use?

Android 13

### What device model do you use?

Pixel 6 (Graphene OS)

### Bug report

https://www.youtube.com/watch?v=t5QDoG-Uams

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
> The Genre tab is always stuttering (probably because of my big library, I have close to 20k songs, mostly in the .opus codec). 

The image grouping algorithm I use is as fast as I can make it, but is forced to run on the main thread due to the image loader library I use. This causes freeze-ups when you have a very large genre with thousands of songs.

> Dragging songs in queue is only smooth if the queue is small enough, otherwise it becomes extremely laggy

Caused by a performance limitation in the list UI component and queue data structure I use. There's no feasible way to fix either of these.

> I forgot to show it in the video, but the search function is fairly slow as well, and there's a noticeable delay when typing letters.

Search is always slow unless you use some fancy data structures that would eat up a good amount of memory.

There's basically nothing I can do about these as it currently stands.
