### ISSUE TITLE
Bug With Library Scanning

### ISSUE THREAD

**Issue by GithubContributor832** [OxygenCobalt/Auxio#58]
#### Describe the bug/crash:

Library scanning is slow and doesn't always pick up changes after reopening the app. Also if I remove all songs from library the widget doesn't automatically refresh the queue in widget. It shows the last played yet deleted song and I have to push play to refresh the queue in widget. Also if a song is currently playing and I delete the whole library the scanning does not work. I have to stop the playing song (how it continues to play is beyond my tech mind) that's deleted then reopen app to get a scan; if I change to any song that's been deleted before I get a scan the app acts psychotic cycling through every deleted song. I have to force stop to get a scan. Besides all this it's outstanding work! 

#### Steps To Reproduce the bug/crash

1. Remove all songs from library leaving a song playing

2.  Scanning does not work unless I stop playing song

3. Play any deleted song before getting scan from stopping currently playing song then the app acts psychotic cycling through each deleted song. Player notification keeps cycling. Force stop to app must be done to get scan.

4. When all songs are deleted from library with scan update the widget doesn't refresh queue automatically as I have to push play on widget to get update

#### Phone Information:
Android 10 

#### Due Diligence:

- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
> Library scanning is slow and doesn't always pick up changes after reopening the app.

Nothing I can do about speed. I never implemented watching the media database for updates as it relies on an extremely clunky API and heavily degrades UX.

> Also if I remove all songs from library the widget doesn't automatically refresh the queue in widget. It shows the last played yet deleted song and I have to push play to refresh the queue in widget. 

Also expected. Again, I don't watch the media database for updates. Plus it's impossible for me to update the widget in certain app states, which results in desyncing.

> Also if a song is currently playing and I delete the whole library the scanning does not work.

Again. Auxio does not respond to MediaStore updates

> I  change to any song that's been deleted before I get a scan the app acts psychotic cycling through every deleted song. I have to force stop to get a scan.

Auxio does all scanning at startup, so you will have to force stop and re-open to get a media scan. As for why it cycles through every deleted song, the media database takes awhile to clean out invalid songs after they are deleted. Auxio will scan these invalid songs regardless since it's impossible to ensure the validity of the file. When the internal player tries to play these songs, it will error out and skip to the next song in an attempt to find a valid song to play. If every song is invalid, it acts in the psychotic way you described.

Every problem with music in Auxio is caused by the horrible state of Android's local media APIs. Pretty much all of them are unfixable. The only way to remedy these issues is by just dropping the "local music player" part of Auxio and making the app stream music from an external server [Think Funkwhale or Subsonic], which I would only do when my music library becomes too big to be practical with the current system.

I'll be merging this into #38 since that's where all the "unfixable" media issues go. Sorry.
