### ISSUE TITLE
doesn't see tracks

### ISSUE THREAD

**Issue by Xbasan** [OxygenCobalt/Auxio#587]
### Describe the Bug/Crash

When opening the application, he does not see a single music file, although the number of songs on the phone is more than 900

### Describe the intended behavior

The program should see all the tracks that I have on my phone, regardless of their number 

### What android version do you use?

Android 13

### What device model do you use?

MIUI 

### Bug report

M

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is likely due to issues with your media database. You can troubleshoot that with the steps [here](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting#music-is-missing-from-the-library). This tends to be very common with OEM skins like MIUI that are poorly coded and thus accidentally break the media database.
