### ISSUE TITLE
Exlude directories from indexing

### ISSUE THREAD

**Issue by Miaourt** [OxygenCobalt/Auxio#6]
Hello, thanks for this app !
I think being able to have a denylist of directories (or maybe an allowlist ?) that are indexed in the app would be interesting !

I'm indeed working with audio files sometime, downloading podcasts too, and I don't want them in the music player app :)

I think this shouldn't bloat the app much, if you take the allowlist path you could simply put the default ~/music folder for example, and if you take the denylist path a simple list of excluded folder would be simple enough to understand I guess 😅

[ x ] I have read  [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) and the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is something I could do. I assumed that the `IS_MUSIC` filter would block out unrelated files, but I guess not.

The caveat here is that it would elongate the loading times, since I would have to now load a database of the blocked directories *and* cross-reference them with the loaded music items. I may study how Phonograph implements the same enhancement and try to implement it in my own system efficiently.

Thanks for the suggestion!

**Comment by OxygenCobalt** [comment]
The exclusion feature has been added as of ~a55b42a. Can you try out this Debug APK and give back any suggestions? [Rename the file to .apk, the excluded directories setting is at the bottom of the settings page]
 
[Auxio-ExcluDir.zip](https://github.com/OxygenCobalt/Auxio/files/6177983/Auxio-ExcluDir.zip)

**Comment by OxygenCobalt** [comment]
The feature has been finished and will be released in 1.3.2 today. Thank you for this suggestion.

**Comment by voussoir** [comment]
Hi @OxygenCobalt, it seems that Auxios excludes the ~/Podcasts folder unconditionally, is that correct? When I rename ~/Podcasts to anything else, the files appear in Auxios, and when I rename it back they disappear. I can't find any use of the word podcasts in the source code so maybe this part of Android's mediaserver.

I was actually hoping to use Auxios just for my podcast files!

**Comment by OxygenCobalt** [comment]
@voussoir I believe this is intentional. Auxio uses the `IS_MUSIC=1` selector when indexing audio files so that certain audio (like ringtones) aren't indexed. By extension, anything in the `Podcasts` folder will not be labeled as music and Auxio excludes them. I might be able to get rid of this and replace it with a pre-defined set of excluded directories, but I'm not sure about how effective that is.

**Comment by voussoir** [comment]
@OxygenCobalt That makes sense, thanks! It's okay, I can just rename the folder. I didn't know android's media framework made that distinction.
