### ISSUE TITLE
Play from search results

### ISSUE THREAD

**Issue by Cwpute** [OxygenCobalt/Auxio#601]
### Description

When playing a title from the search results, i'd like the queue to switch to the search results that came up.

### Problem solved

I have a common issue with recognizing media, and more specifically, folders in which they are located. If i name my files with a common denominator (the artist or album name for example) then i can find them all easily with one search. But i can't play the whole of them quickly from the search results i just got!
Now if i was able to play from the search results, i could play the whole thing easily.

Another example would be live version of songs: most of the time it's named in the title, but not as tags. Searching for `live` and playing from the results would allow to have them all in the queue right away!

Also i have a lot of downloaded 🙃 versions of songs that are not correctfully tagged. It would be a huge undertaking to tag everything back to a usable level. Now if for some reason some information about the song is contained in its title, then it's easier to search for that common information and play from the results.

### Other implementations

Alternatively, there could be an option to add all the search results to the queue. This option could even coexist with the one i'm suggesting, as it would

### Benefit

Allow for more uses and flexibility in the way people interact with Auxio!

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I don't see myself adding this. It's one of those features that accommodates poorly tagged libraries, which is something I don't do since it massively increases the complexity of the app internally and results in a much worse configuration experience. Consider how many settings Poweramp has to accommodate every possible strange tagging format in a library. Sorry.

I think you would benefit from auto-taggers like [beets](https://beets.io/) and [MusicBrainz Picard](https://picard.musicbrainz.org/). They solve the problem of tagging being tedious by having a registry of metadata tied to the exact auditory fingerprint of the music file. This way, you would be able to fully leverage Auxio's well-tagged library support in just a few minutes.

**Comment by Cwpute** [comment]
Unfortunately, those music tagging apps are only available on computers… not on Android 😕 and there are currently no opensource or privacy-aware apps on Android that would do the same thing.

Thanks for your detailed and argued answer !
I understand your point of view, and will return to my corner to sob with my untagged, messy music library (jk).

**Comment by OxygenCobalt** [comment]
MusicBrainz also has an app at https://f-droid.org/en/packages/org.metabrainz.android/.

**Comment by Cwpute** [comment]
> MusicBrainz also has an app at https://f-droid.org/en/packages/org.metabrainz.android/, if that helps.

Sorry no it doesn't 😕 i have asked on their forum yesterday and the MusicBrainz app doesn't tag in bulk anymore. The Picard app is not available on Android and won't be ever unless someone decides to take this matter into their own hands.
Nobody there knovs about apps that can tag in bulk efficiently on a smartphone either. I'm a bit stuck here!
