### ISSUE TITLE
Theme color from Album Art

### ISSUE THREAD

**Issue by VishnuSanal** [OxygenCobalt/Auxio#616]
Requesting for a feature to extract color from album art to use as the accent color for the app.

PS: I'd like to work on this :)

**Comment by OxygenCobalt** [comment]
You can work on it, but I likely won't merge it into the mainline Auxio branch. The problem is that:

1. You cannot dynamically modify theme at runtime without a huge and brittle theming infrastructure that would cause bugs. This is also why Auxio's accent palette is fixed.
2. There's no maintained or official library to extract the monet color palette of an image. There are a few toy projects that I don't really want to bring into my app since they may be unreliable.

Sorry.

**Comment by OxygenCobalt** [comment]
Okay, so number 2 is no longer valid, MDC [supports dynamic extraction](https://github.com/material-components/material-components-android/blob/master/docs/theming/Color.md#content-based-dynamic-colors) using the new color palettes. Still unsure at whether I want to do it.
