### ISSUE TITLE
Add a floating player for files-manager

### ISSUE THREAD

**Issue by Richard38907** [OxygenCobalt/Auxio#618]
### Description

A floating player like this:
I use v 3.2.1
![Screenshot_20231119-095859_Musique](https://github.com/OxygenCobalt/Auxio/assets/148692265/36df58b8-b8bf-4d59-a7b7-79f672022ceb)

### Other implementations

I use LineageOs 6.0.0 beta music player on the screenshot.
No "draw over the apps" permission needed.

### Benefit

You can quickly select a song from file manager and quit that song by touching outside the popup.
~20% of the music players I tested contain this feature

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
As it currently stands, this is largely impractical. There issue is that:

1. I would need to instantiate music playback in the foreground with this dialog. This is already difficult to implement, but since users will expect the ability to fully open the song in-app, I would then have to move it to the background in a process I'd imagine would be extremely fragile.
2. I'd imagine most users would want more than merely the file name in this floating dialog, but this is not possible with the current architecture, as songs are inseparable from the rest of the music library that they were loaded with.

Both of these major refactors would likely create a lot of bugs for a very minimal benefit. In general, Auxio isn't designed for file-based playback anyway. It's more designed around well-tagged libraries, hence the basic behavior when a file is opened.
