### ISSUE TITLE
Add support for Replaygain 

### ISSUE THREAD

**Issue by h4xor666** [OxygenCobalt/Auxio#7]
#### Describe the feature you want to implement:

A toggle for enabling replaygain
#### Is your feature request related to a problem? Please describe:
Yes, replaygain solves the problem of different tracks sometimes being different levels of volume, and it normalizes the volume.

Sometimes tracks in an album can be different levels of volume, or tracks in a playlist. 
#### Why do you think this will improve everyone's usage of Auxio?

For users who have their music with replaygain tags, definitely. Many users on Android who store their music locally use Replaygain.
#### Due Diligence:

- [ X] I have read  [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) and the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I'm not sure how to enable that exactly using ExoPlayer (Which is the media player I use). Can you provide an example of another android music player that has that feature?

**Comment by h4xor666** [comment]
I am a dummy so I have no clue how things work lmao. I appreciate your response though.

**Comment by OxygenCobalt** [comment]
Yeah, I don't think that Android supports this natively. In a future version it could be possible but for now I think your options are either Vanilla or (Maybe) PowerAMP.

**Comment by breversa** [comment]
I'd love to see ReplayGain support too (I've used Vanilla Music but the UI needs overhauling, and it lacks a working "play when headset is plugged in" feature for recent Adnroid versions).

[Foobar2000 Mobile](http://mobile.foobar2000.com/) has such a feature too but as far as I know it's closed source.

**Comment by OxygenCobalt** [comment]
Sadly, nothing has still changed on this front. The only way I could feasibly support replaygain is either by:

A. Streaming music via SoundPod as we can let the music server handle it, but such an change is incredibly far away.
B. Completely replacing the music backend with my own metadata parser instead of android's built-in media database, but that also impractical right now for reasons I described in the [the media indexing issues thread](https://github.com/OxygenCobalt/Auxio/issues/38#issuecomment-948988954).

**Comment by breversa** [comment]
(For some reason, this current issue isn't searchable from https://github.com/OxygenCobalt/Auxio/issues?q=is%3Aissue+is%3Aclosed :thinking: )

**Comment by OxygenCobalt** [comment]
Actually, I could possibly support replaygain. I believe ExoPlayer exposes some APIs for music metadata that are loaded with the file itself. If the API exposes raw music tags I could probably be able to get the replaygain information and adjust the player volume based on that. I'll be re-opening this issue and investigating this further.

**Comment by breversa** [comment]
That would be awesome ! :heart_eyes: 
I'm no developer but I volunteer to test your app and provide feedback as needed. :D

**Comment by OxygenCobalt** [comment]
Okay, I've determined this is possible and I'll try to implement it. A couple caveats though:

1. Depending on how fast the tags are loaded, the volume might change a bit into playback. Nothing I can do about this.
2. This will only likely work for MP3/FLAC files.
3. This will be gated behind a settings option since I have no idea how stable this will be.
4. Auxio will only read  `replaygain_track_gain` [or similar] tags and then treat the adjustment in decibels. No funky ID3-specific junk.

**Comment by OxygenCobalt** [comment]
@breversa Hey, do you have a MP3 file with ReplayGain tags? I'm not sure how to parse them outright.

**Comment by breversa** [comment]
Of course !

There you go : https://ecloud.global/s/zaZW4eH55wxz93P

**Comment by breversa** [comment]
And here's for a FLAC file : https://ecloud.global/s/NjR38sk3TggaJ2z

**Comment by OxygenCobalt** [comment]
Cool! Thanks for the tool as well.

**Comment by OxygenCobalt** [comment]
@breversa Can you try this APK? I've made an implementation that supports the basic `REPLAYGAIN_TRACK_GAIN`, `REPLAYGAIN_ALBUM_GAIN`, `R128_TRACK_GAIN`, and `R128_ALBUM_GAIN` tags. Let me know if it sounds right, and then I'll commit the change.

As soon as this implementation is pushed, I'll add a configuration option for the feature, so you can switch the priority [track/album] and whether the feature is enabled at all. 

**Note:** You have to rename the extension to .apk to install it.

[Auxio_ReplayGain.zip](https://github.com/OxygenCobalt/Auxio/files/7823693/Auxio_ReplayGain.zip)

**Comment by breversa** [comment]
At once !!

**Comment by breversa** [comment]
Damn that's awesome ! It so great to NOT have to change the volume on each (random) track change ! :D THANK YOU !!

(I still miss ReplayGain support for Ogg Vorbis files stored in [VORBISCOMMENT](https://en.wikipedia.org/wiki/Vorbis_comment) IIRC, but I'm being picky !)

**Comment by OxygenCobalt** [comment]
Fantastic! I'll commit the change.

> (I still miss ReplayGain support for Ogg Vorbis files stored in VORBISCOMMENT IIRC, but I'm being picky !)

Let me look into this. ExoPlayer supports OGG, it just calls all the metadata it indexes "FLAC Metadata" for whatever reason.

**Comment by OxygenCobalt** [comment]
Can you provide an OGG with a VORBISCOMMENT ReplayGain tag? I can't imagine it would be too hard to add to my ReplayGain implementation/

**Comment by breversa** [comment]
I just noticed something weird : if I get a notification (e.g. Signal message) while music is playing, once the notification sound is over, music playback volume seems reset (= no gain applied) and sounds louder.

Skipping to the next track corrects it, but pause/play doesn't.


Yes, I'll provide you with an Ogg Vorbis file.

**Comment by OxygenCobalt** [comment]
Oh shoot. I forgot about notification ducking. Let me fix that.

**Comment by breversa** [comment]
Here's an Ogg Vorbis file : https://ecloud.global/s/JME58Nnk6GSfznt
(It's THE track that got me into the goth/futurepop scene ! ^^)

**Comment by OxygenCobalt** [comment]
Ah, ExoPlayer can't parse OGG for some reason, despite it being nearly identical to FLAC's format. This is sadly the cost of using ExoPlayer here, very little non-streamed metadata formats are actively read by the player. However, it's either that or parsing metadata myself, so I may as well pick the former.

Heres an updated APK with the notification issue fixed:
[Auxio_ReplayGain_Fixed.zip](https://github.com/OxygenCobalt/Auxio/files/7823895/Auxio_ReplayGain_Fixed.zip)

**Comment by breversa** [comment]
It works ! Thanks !! :D

**Comment by OxygenCobalt** [comment]
Quick note: I identified another issue. If a notification shows up as one song transitions into another, the volume adjustment will not work correctly. I'm working on fixing this. Expect more issues as I try to debug this system.

**Comment by OxygenCobalt** [comment]
This APK contains the mostly finalized ReplayGain implementation, with customization enabled and the ducking issues fixed, alongside the improved audio focus mechanism that I added trying to fix the former.

Some notes about this:
- ReplayGain is not enabled by default. This is because the feature is somewhat obscure and only works on two file formats.
- There might be a slight delay between updating the ReplayGain setting and the change taking effect. This is because the player is only watching for volume changes every 500 milliseconds. I could make that interval shorter, but that risks high resource consumption.
- I'll try to add OGG in the future. It's a matter of parsing metadata myself, which could range from somewhat difficult to borderline impossible depending on how much ExoPlayer wants to get in my way.

This feature will arrive in 2.1.0. Some other changes might be made from here to the release of, but this contains an implementation that I think is suitable for normal use. Have fun. 

[Auxio_ReplayGain_Final.zip](https://github.com/OxygenCobalt/Auxio/files/7825047/Auxio_ReplayGain_Final.zip)

**Comment by breversa** [comment]
I'm so grateful of your work, @OxygenCobalt !!! :heart: 

I now declare Auxio my #1 Android audio player, thanks to these features that no other player combines:
1. Simple/ergonomic UI
2. Autoplay when plugging headphone
3. ReplayGain support
4. Open-source

**Comment by OxygenCobalt** [comment]
Hey, good news: I found a way to get files with VORBISCOMMENT ReplayGain tags working. Turns out ExoPlayer can already parse those tags from OGG files and just...doesn't expose them. So, I created a [fork](https://github.com/oxygencobalt/ExoPlayer) of ExoPlayer that exposes the metadata, and after including that dependency OGG Files seem to work now. I attached an APK below. 

[Auxio_OGG_Replaygain.zip](https://github.com/OxygenCobalt/Auxio/files/7835699/Auxio_OGG_Replaygain.zip)

**Comment by breversa** [comment]
Great ! I'll give it a try (maybe not today though) and report back ASAP. :)

**Comment by CorePoint** [comment]
Great to hear that you implemented Replaygain, I think your project is the only one that uses exoplayer and supports replaygain!

I have another feature request which I don't really know how hard it would be to implement.
It would be great if Auxio would recognize if you are listening to an album, or just a playlist with mixed tracks and switch the replaygain mode accordingly.
I got the idea from [this foobar2k plugin](https://www.foobar2000.org/components/view/foo_dsp_replaygain).

Have a good day and thanks for your work!

**Comment by breversa** [comment]
> @breversa good news: I found a way to get files with VORBISCOMMENT ReplayGain tags working. Turns out ExoPlayer can already parse those tags from OGG files and just...doesn't expose them. So, I created a [fork](https://github.com/oxygencobalt/ExoPlayer) of ExoPlayer that exposes the metadata, and after locally depending on that, OGG Files seem to work now. I attached an APK below.
> 
> [Auxio_OGG_Replaygain.zip](https://github.com/OxygenCobalt/Auxio/files/7835699/Auxio_OGG_Replaygain.zip)

Hi @OxygenCobalt ! Forgot to say that I tried your Vorbis-compatible version and, as expected, it works fine. So once again, a huge THANK YOU ! I'm eager to see this feature in the production build so that I can recommend it to my friends !

**Comment by breversa** [comment]
> Great to hear that you implemented Replaygain, I think your project is the only one that uses exoplayer and supports replaygain!
> 
> I have another feature request which I don't really know how hard it would be to implement. It would be great if Auxio would recognize if you are listening to an album, or just a playlist with mixed tracks and switch the replaygain mode accordingly. I got the idea from [this foobar2k plugin](https://www.foobar2000.org/components/view/foo_dsp_replaygain).
> 
> Have a good day and thanks for your work!

Could it be as simple as:
```
if (previoustrack.album == currenttrack.album) then
  replaygain = album
else
  replaygain = track
```

?

**Comment by CorePoint** [comment]
@breversa 

Wouldn't catch every case, but if it would consider maybe the previous and last two tracks it probably would be a "good enough" solution.

**Comment by CorePoint** [comment]
@OxygenCobalt 

I'm very impressed by your openness to suggestions and your quick responses.
As far as I know this dynamic feature is non existent on mobile devices as of now.
Thank you again! :)

**Comment by OxygenCobalt** [comment]
I just realized: ReplayGain tags that *increase* volume won't work, as they will need the volume to be increased above 1.0. Theoretically here I can just add my own `AudioProcessor` that allows a volume higher than 1.0. This can wait for now though, as files that need to gain volume are far less common.

**Comment by breversa** [comment]
Indeed, I have only seldom encountered tracks that had a below-reference volume level. I don't think it'll be a common issue but it's good to know about this limitation. Maybe add this comment in the ReplayGain option menu UI ?

**Comment by OxygenCobalt** [comment]
Yeah, I've tried my hand at implementing an `AudioProcessor` based on [this issue](https://github.com/google/ExoPlayer/issues/6090) and it seems to be far too risky given that if I forget a format or fiddle with the bytes incorrectly, very bad things could happen. I would need test files that emit every possible output encoding before I could add it. I've already marked the limitation in the FAQ, so I may as well leave this implementation as-is until someone actually requests the feature.

As for other formats I've found are actually supported, I can also add MP4 (with an `ID32` atom) to the list of supported formats as well. Turns out ExoPlayer actually parses those tags.

**Comment by OxygenCobalt** [comment]
Okay, I decided to add support for files with positive ReplayGain values. This mostly stemmed from me having to migrate the ReplayGain engine to an `AudioProcessor` due to some other changes that would also cause conflicts if I used the normal volume field. I hope it works out.

**Comment by Donkey-Doug** [comment]
@OxygenCobalt Maybe rename "ReplayGain" to "Normalize volume"

**Comment by OxygenCobalt** [comment]
@Donkey-Doug Why? I think ReplayGain is clearer since it actually describes where Auxio is getting volume normalization data. Without it, the setting is unclear and could mislead users into thinking that the normalization process is automatic.

**Comment by breversa** [comment]
Agreed with @OxygenCobalt.
Also, as an "amateur" audiophile and non-native english speaker, "Normalize volume" doesn't tell me as much information as "Replaygain".

**Comment by lord-ne** [comment]
I agree that "Replaygain" gives.more information than "Normalize Volume", but I think something like "Replaygain (Normalize Volume)" would give the best of both worlds. That way if someone happens to see the setting, they'll know vaguely whether or not it's something they're interested in, and if they are then they know to google ReplayGain for more info

**Comment by snwflake** [comment]
> @Donkey-Doug Why? I think ReplayGain is clearer since it actually describes where Auxio is getting volume normalization data. Without it, the setting is unclear and could mislead users into thinking that the normalization process is automatic.

To be fair, the current naming lead me to believe the same, which is the reason I'm here right now.... x)
though gonna add tags to my entire library now and enjoy it working.
