### ISSUE TITLE
Not detecting songs

### ISSUE THREAD

**Issue by dhishkyaon** [OxygenCobalt/Auxio#71]
so if i download a new song Auxio does not detect it automatically. It only shows the songs that were downloaded before storage permission was given. I have to clear storage for Auxio to make it detect the song.

OS: Android 12
Device: Pixel 4a
Version: 2.1.0

**Comment by OxygenCobalt** [comment]
This is a limitation with the way Auxio loads music. Right now, you have to force-stop the app from the settings menu and then restart the app for it to re-scan the music library. The same thing happens when you clear the app storage. I want to eventually add a setting that at least makes this more obvious.

It *may* be possible for Auxio to do periodic re-indexes whenever the media library changes, but it would require major internal changes to work out properly. I'll keep it in mind though.

**Comment by dhishkyaon** [comment]
yeah. its a very obvious feature in a music player.

**Comment by OxygenCobalt** [comment]
True. I've just never found the use for it given how little I update my music library [I usually do it in large batches]. I'll keep this open until I get a stopgap option implemented.

**Comment by OxygenCobalt** [comment]
I've added an option that will hard-restart the app, similar to what would happen if you clear the app storage. This will result in a rescan of the library with only a minor interruption in playback.

I'll create a dedicated issue for what I'll only call "Automatic Rescanning", just to let people know that I am aware of it.
