### ISSUE TITLE
Unknown freezing occuring at random

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#729]
Current theory is a deadlock that occurs when the state is saved right when some other playback operation occurs. Not really sure why.

**Comment by lriesebos** [comment]
Does this occur for example when the player moves on to the next track in the playlist? Since version 3.4.x I noticed that the player just stops playing music at some point when shuffling all songs. I think it occurs only when moving to the next track and the slider just stays at the left. One way to solve that is to again press the "shuffle all" button to start playing a new shuffled playlist.

**Comment by OxygenCobalt** [comment]
Seems like a different error to what I'm talking about. Can you provide a bug report @lriesebos the moment the issue appears again? See [here](https://developer.android.com/studio/debug/bug-report) for instructions. You can also enable "Bug report shortcut" in developer settings on some devices that should allow you to open the power menu and then select the "Bug report" option, which might be helpful to allow you to immediately take a bug report when the error appears again.

**Comment by OxygenCobalt** [comment]
I can't seemingly reproduce this, any nobody has come forward. Closing it until it appears again.
