### ISSUE TITLE
Rounded corners broken on thin widget

### ISSUE THREAD

**Issue by olivkauwu** [OxygenCobalt/Auxio#730]
### Description

I miss old widget design, earlier I could see track name and also it looked great, now I just can see album cover, no track info and also it doesn't look great with my theme. Please can you maybe add a option for alternative widget? Or maybe add track info on newer version, and monet on it looked really great. I see that there is more media buttons now, but me and maybe some users would prefer more old design. (I'm new to github, sorry it isn't place to ask this)

Photos of how it looked earlier 
![IMG_20240227_150508_686](https://github.com/OxygenCobalt/Auxio/assets/152069398/770cd3a3-185b-4e89-9e22-738868bf7208)

and now 
![IMG_20240227_150524_294](https://github.com/OxygenCobalt/Auxio/assets/152069398/a5e0d3ad-933f-42f6-b3b3-bd0612fbff21)

### Other implementations

It was great in older Auxio version 

### Benefit

It will give more useful information on a widget

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I had to change the widget design to properly accommodate the new thin widget functionality. In general, the old design was solely designed for an edge case in landscape mode, and was only able to display track information by removing an excessive amount of controls. Generally I think music controls are more useful in general than having a bunch of song information, so the new design was control-oriented like other layouts.

I don't really see myself adding a way to switch back to the old widget. I am extremely hesitant to add new widget styles since it's extremely hard to maintain widgets that I won't regularly use. Having a single canonical design reduces the amount of bugs overall. New widget styles also act as precedent for even more widget styles, compounding the problem. I have gone back and forth on a text-based widget, but I can't meaningfully create a generalized design for that that will look good.

The only thing I am going to fix is the cover having sharp corners. That is not intended, and I imagine it's the result of your specific launcher not cropping the widget at all. I can go fix that and it should look a little better.

**Comment by Mischievous-Loner** [comment]
Widget doesn't load for me if forced 1:1 square album cover is enabled.

**Comment by OxygenCobalt** [comment]
Screenshot? @Mischievous-Loner

**Comment by olivkauwu** [comment]
> I had to change the widget design to properly accommodate the new thin widget functionality. In general, the old design was solely designed for an edge case in landscape mode, and was only able to display track information by removing an excessive amount of controls. Generally I think music controls are more useful in general than having a bunch of song information, so the new design was control-oriented like other layouts.
> 
> I don't really see myself adding a way to switch back to the old widget. I am extremely hesitant to add new widget styles since it's extremely hard to maintain widgets that I won't regularly use. Having a single canonical design reduces the amount of bugs overall. New widget styles also act as precedent for even more widget styles, compounding the problem. I have gone back and forth on a text-based widget, but I can't meaningfully create a generalized design for that that will look good.
> 
> The only thing I am going to fix is the cover having sharp corners. That is not intended, and I imagine it's the result of your specific launcher not cropping the widget at all. I can go fix that and it should look a little better.

Maybe u can do similar design to Apple Music?
![Screenshot_20240228-224536](https://github.com/OxygenCobalt/Auxio/assets/152069398/ebdb931a-0c06-44b4-80d3-e4ef2b0771c1)

**Comment by olivkauwu** [comment]
> That doesn't adhere to Material design 3 guidelines (Mostly in spacing), so either it would have to use an inconsistent spacing compared to everything else or would look squished into oblivion.

So, no? I think it will look great, and also it has all necessary buttons and track info

**Comment by OxygenCobalt** [comment]
Yes, it's not really an option. The issue is that apple uses a completely different design system that with extremely small layout spacing, which is not recommended under Material Design 3.

**Comment by OxygenCobalt** [comment]
The widget should be at least properly rounded in 3.4.2.
