### ISSUE TITLE
add a "refresh/rescan music" button to toolbar_home

### ISSUE THREAD

**Issue by dagithubun** [OxygenCobalt/Auxio#740]
### Description

something like a reload button in the top right corner of the toolbar to quickly do the function of the "Refresh music" or "Rescan music" instead of having to go to settings every time.

### Other implementations

-

### Benefit

it would be a much nicer and quicker way.
thanks for your precious work.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
There are already too many buttons present on the home screen for this to be implemented, sadly. I put those options into the settings menu additionally since I want to clearly differentiate refreshing and rescanning music given that both are useful in different circumstances, and would be confusing as a menu item. Sorry.
