### ISSUE TITLE
[Accessibility] Activated / deactivated shuffle not well distinguishable

### ISSUE THREAD

**Issue by heuwerk** [OxygenCobalt/Auxio#745]
### Description

Hello dear Auxio team,
thank you very much for your work, I would like the readability of the current state of the repeat and shuffle buttons to be improved.

In the current version, the active buttons are only slightly thicker, which makes it difficult to distinguish them.
![auxio_shuffle_off](https://github.com/OxygenCobalt/Auxio/assets/75751604/7bc37af5-6ab9-4dfd-bac5-8392676ca637)
![auxio_shuffle_on](https://github.com/OxygenCobalt/Auxio/assets/75751604/a1ef2f15-1d88-47d4-b231-6d8e40bc6429)

### Other implementations

In Spotify, for example, the button is displayed in a different color and highlighted with a dot when the shuffle is activated.
![spotify_shuffle_on](https://github.com/OxygenCobalt/Auxio/assets/75751604/52559a83-8c13-45a1-8a26-32cd115e19f9)

This makes it much easier to recognize the current status.

### Benefit

I think this change would improve the experience for many users as it is sometimes a guessing game whether shuffle/loop mode is enabled or not.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is actually the recommended way to indicate an active state as per [Material Design](https://m3.material.io/styles/icons/applying-icons#a81d4b30-9f2c-4ae2-9101-ac51c713ce28). Additionally, other alternatives will not consistently work without being visually strange.
- A dot cannot work in all contexts. Notifications would require me to embed it into the icon itself, and there is not enough space available for me to do that without shrinking it and making it look weird.
- I cannot dim the icon, as that will confuse it's state for it being disabled.
- Otherwise willing the background of the icon will run into the same limitations as 1, and generally looks more intrusive.
- I cannot make the off icon thinner without becoming inconsistent with all other icons.

Sorry.
