### ISSUE TITLE
Don't allow duplicate songs in playlists

### ISSUE THREAD

**Issue by nitinsooni** [OxygenCobalt/Auxio#799]
### Description

Self-explanatory 

### Other implementations

...

### Benefit

...

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I'm not going to disallow it, but I will likely warn against it. I would rather be more liberal with how playlists can be used.

**Comment by OxygenCobalt** [comment]
That already exists at #747

**Comment by OxygenCobalt** [comment]
I need the stack trace @nitinsooni, please click the more button and copy the information to here.

**Comment by OxygenCobalt** [comment]
Ah, this error again @nitinsooni. Some OEMs don't allow me to start foreground services even when I'm allowed to. This is sometimes a timing issue, but I have the hunch that it's deliberate on behalf of some OEMs as to make third party apps less desirable compared to the baked-in OEM bloatware that coincidentally just...doesn't suffer from the same issues.

**Comment by OxygenCobalt** [comment]
> That loading dialog on startup which groups everything up in-memory on startup, maybe caching that also would be good Idea because i didn't see any performance issue with other foss music players or proprietary ones like samsung music. They just opens and works fine.

Perhaps. I don't know whether a query over a big database will be more efficient, but perhaps grouping is far less efficient than I realized.

Not budging on in-memory loading though.

> And that error, you have any fix for that? Because it now just occurs like ever alternate day and its take lot of time to load around 5000 songs.

Nope. It's usually your phone. I assume it's a Samsung given that you brought up their app. They are notorious for killing foreground services for no reason and otherwise making things miserable for third-party apps. My theory is that this is intentional throttling to make you use Samsung Music (Which is also loaded up with ads like other awful Samsung bloatware). The most I can do is artificially introduce a delay in startup to appease their terrible ROM, but that means you need to wait another couple of seconds until loading stops.

**Comment by OxygenCobalt** [comment]
There's no real fix @nitinsooni. Just stop getting samsung and get a pixel instead, which doesn't suffer from this.

**Comment by Hund** [comment]
I would love to see some message telling me about adding a duplicate song or not. I find it quite annoying to have the same tracks multiple times in my playlists.
