### ISSUE TITLE
Add widget support

### ISSUE THREAD

**Issue by GithbUser** [OxygenCobalt/Auxio#8]
Title is self-explanatory

Add different widgets, such as 4x2, 4x1, text only, etc.

**Comment by OxygenCobalt** [comment]
I could do this, but I'm not sure how compatible with the architecture of my app it could be. I never exactly designed my app with the idea that some UI element could exist outside of the main app process, so adding widgets might require me making a ton of changes to the internal structure. I'll look into it.

**Comment by GithbUser** [comment]
If this require this lots of work to do,you can add this feature later.
Widget isn't fully necessary but it allows users to play music in one tap without opening app

Also all music players have this feature included 

Take your time and thanks for developing app

**Comment by OxygenCobalt** [comment]
Good point. Ill see what I can do.

**Comment by OxygenCobalt** [comment]
Update: Since Android 12 is introducing new widget tooling, I'll begin work on this feature once that version reaches the "Platform Stability" milestone. It may not be for me, but it seems like the benefits outweigh the costs, especially with this new drive to make widgets first-class again.

**Comment by OxygenCobalt** [comment]
This is my plan for widgets as of right now:

- I'll design them with the upcoming Android 12 in mind, so they'll have to be cohesive with the other widgets in that version 
- Widgets will follow the theme/accent on all versions except for Android 12, which will use the Material You theming system

There will be four types of widgets:
- **Full:** basically the full playback screen [Album art, text, play/shuffle/skip/shuffle/loop]
- **Compact:** smaller, only contains the album art, text, and play/pause/skip buttons
- **Minimal:** only the album art is displayed, no controls or info is present
- **Terminal:** like minimal, but text-only instead

The latter two may change, but this seems to work well.

**Comment by OxygenCobalt** [comment]
Done. I decided to actually go for a single responsive widget instead of multiple types, not only because that's the recommended method to do them in Android 12, but also because it makes creating UIs that don't suck a lot easier. Here it is:

![widgets](https://user-images.githubusercontent.com/65370175/128423654-7efc275d-3bf0-4f95-8c81-5ae9cd983d07.gif)

Some more changes will probably be needed in the backend, but this is likely the final widget design. The widgets do work on all versions [including the more responsive aspects], and the UX is relatively rational. This addition will arrive in the next release.
