### ISSUE TITLE
Disabling auxio service

### ISSUE THREAD

**Issue by skyperson1080** [OxygenCobalt/Auxio#807]
### Description

I don’t like the background process called auxio service, everything worked fine without it, but now it hangs in the background

### Other implementations

If I'm not mistaken, there is a setting for this

### Benefit

There will be no unnecessary waste of resources

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
The auxio service has existed since version 1.0.0. My assumption is that you recently upgraded to android 14 and noticed that Auxio was in the "N apps are active" screen and thought I added that. The auxio service is required for the app to do fundamental behaviors like play music in the background.

Generally, Auxio's RAM use is most inefficient with its in-memory music library and image caching. However, these result in much snappier user experiences compared to keeping it all on-disc. Memory is usually more abundant than CPU time on android. The user interface does not consume much memory at all.

1by1 appears to be EXTREMELY outdated. Its android app seemingly has not been updated since 2021, it's stuck on a very old API version (likely pre-marshmellow since it's delisted on google play), and it's using kitkat-era UI components. That is not the direction I want to go in with Auxio. Sorry.
