### ISSUE TITLE
Widget don't load if album cover image is square (1:1)

### ISSUE THREAD

**Issue by Mischievous-Loner** [OxygenCobalt/Auxio#828]
### Describe the Bug/Crash

Widget don't load if album-song cover image is square (1:1) by default or you have enabled it from the settings.
It works if cover image is rectangular.
It used to work till version **3.3.3**
![Screenshot_20240714-205624](https://github.com/user-attachments/assets/ab6f5fa2-f014-49d2-825a-18c7d5340141)
![Screenshot_20240714-205544](https://github.com/user-attachments/assets/eb61b8cf-1091-45f6-823b-7f301c3e6e14)

### Describe the intended behavior

Widget Should load regardless the cover image aspect ratio.
It worked till version 3.3.3

### What android version do you use?

Android 14

### What device model do you use?

Lava blaze 5g
It uses stock android.
No skin.

### Provide a sample file

[songs.zip](https://github.com/user-attachments/files/16227935/songs.zip)

### Bug report

Incoming call, so I will put it in another comment below 

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by Mischievous-Loner** [comment]
Bug report 
https://mega.nz/file/lzh0gYpJ#GL-TPgT-SnkXTvUWwaUANBiui_9SYRNJViAe5S_PiwI

**Comment by shashankmunda** [comment]
@Mischievous-Loner seems like you're using a custom launcher, have you checked if it's a problem with the launcher?

**Comment by Book-reader** [comment]
I can reproduce this on an oppo A54s on ColorOS 13 with the default launcher & Auxio 3.5.2

https://github.com/user-attachments/assets/cd6ad56a-a7c6-4bb9-a039-dde0fe0faecc

https://github.com/user-attachments/assets/770716b2-bb1b-4f04-98fb-d0fded2d5fb3

https://github.com/user-attachments/assets/ea521e44-dbb0-4d4d-a321-a656bee41914

**Comment by OxygenCobalt** [comment]
Thanks for reporting this @Mischievous-Loner @Book-reader, will take a look

**Comment by Mischievous-Loner** [comment]
It's same with default device launcher

**Comment by OxygenCobalt** [comment]
[Auxio_Canary.zip](https://github.com/user-attachments/files/16322317/Auxio_Canary.zip)

Can you please take a [bug report](https://developer.android.com/studio/debug/bug-report) from this APK @Mischievous-Loner @Book-reader

**Comment by Book-reader** [comment]
[bugreport-CPH2273-TP1A.220905.001-2024-07-21-09-43-23.zip](https://github.com/user-attachments/files/16322445/bugreport-CPH2273-TP1A.220905.001-2024-07-21-09-43-23.zip)

**Comment by OxygenCobalt** [comment]
Identified it @Book-reader, android can't handle widgets with bitmaps that are too big, and it seems like your device is erroring out when that happens. It only happens with non-1:1 covers I imagine because of the extra pixels added by them. I need to reduce the size limit. For now reduce the size of the covers in your music files and/or switch Settings -> Content -> Album covers back to fast.

**Comment by OxygenCobalt** [comment]
Care to try the APK in this ZIP file @Book-reader @Mischievous-Loner?

[Auxio_Canary.zip](https://github.com/user-attachments/files/16322807/Auxio_Canary.zip)

**Comment by Book-reader** [comment]
It still behaves the same (with fast ambum covers as well)

https://github.com/user-attachments/assets/b738c928-fa65-449c-baa3-53c99495113d

**Comment by OxygenCobalt** [comment]
Sorry, messed up the fix, try this @Book-reader @Mischievous-Loner

[Auxio_Canary.zip](https://github.com/user-attachments/files/16323015/Auxio_Canary.zip)

**Comment by Book-reader** [comment]
It is still the same
I also tested with a 4k 16:9 png upscaled 4x & a 5x5 png and the results were the same in both 3.5.2 & the debug build

https://github.com/user-attachments/assets/2ff01685-1f6b-4489-9878-8fd949722aaa

![Screenshot_2024-07-21-17-13-01-50_b783bf344239542886fee7b48fa4b892](https://github.com/user-attachments/assets/a039e555-dea2-4344-a709-826b04df94fa)

**Comment by Book-reader** [comment]
I also noticed that the album covers do not get refreshed in either build when pressing the rescan music button

**Comment by OxygenCobalt** [comment]
Alright @Book-reader, my assumption is that this isn't a simple device-specific variation but instead your phone having the Android 12/13 bug where Android thinks the widget's album cover takes up far more space than it actually does. It only appeared in the newer versions since I added new widget layouts.

I can only mitigate this by drastically reducing album cover resolution, which will make it really blurry.

**Comment by sakuranonamida** [comment]
Same happened with my phone (stock launcher, vivo y31, funtouch os 13)

**Comment by OxygenCobalt** [comment]
Can you try this @Book-reader @Mischievous-Loner @shashankmunda? I made the album cover size patch much more drastic:

[Auxio_Canary.zip](https://github.com/user-attachments/files/16370214/Auxio_Canary.zip)

**Comment by Book-reader** [comment]
The album cover does appear, but as you said is very blurry
<details>

![Screenshot_2024-07-25-16-13-17-05_b783bf344239542886fee7b48fa4b892](https://github.com/user-attachments/assets/a6fca418-5d7c-4498-a5c7-9ab0b42a31d4)

</details>

**Comment by OxygenCobalt** [comment]
> The album cover does appear, but as you said is very blurry
> <details>
> 
> ![Screenshot_2024-07-25-16-13-17-05_b783bf344239542886fee7b48fa4b892](https://github.com/user-attachments/assets/a6fca418-5d7c-4498-a5c7-9ab0b42a31d4)
> 
> </details>
> 

As I thought. This is indication that your phones ROM has not patched the bitmap size bug. There is nothing I can do

I can only assume at this point to basically just disable the covers on smaller widget forms as needed and make it progressively less usable.

**Comment by OxygenCobalt** [comment]
Try this @Book-reader @Mischievous-Loner @sakuranonamida?

[Auxio_Canary.zip](https://github.com/user-attachments/files/16420609/Auxio_Canary.zip)

**Comment by sakuranonamida** [comment]
> Try this @Book-reader @Mischievous-Loner @sakuranonamida?
> 
> [Auxio_Canary.zip](https://github.com/user-attachments/files/16420609/Auxio_Canary.zip)
> 
Still the same and it doesn't work:(

**Comment by OxygenCobalt** [comment]
Confusing, can you take a bug report @sakuranonamida?

**Comment by sakuranonamida** [comment]
> Confusing, can you reproduce the bug and then take a [bug report](https://developer.android.com/studio/debug/bug-report) afterwards @sakuranonamida?

[bugreport-CPH2273-TP1A.220905.001-2024-07-21-09-43-23.zip](https://github.com/user-attachments/files/16467163/bugreport-CPH2273-TP1A.220905.001-2024-07-21-09-43-23.zip)

**Comment by OxygenCobalt** [comment]
I might have uploaded the wrong build, trying again @shashankmunda @Mischievous-Loner @Book-reader 

[Auxio_Canary.zip](https://github.com/user-attachments/files/16477715/Auxio_Canary.zip)

If it still doesn't work, reproduce and then immediately take a [bug report ](https://developer.android.com/studio/debug/bug-report) again.

**Comment by Mischievous-Loner** [comment]
Sorry for not replying, was really busy with work.
The above Auxio_Canary works perfectly for me.
Thank you very much.
👏🏼🫡

**Comment by Mischievous-Loner** [comment]
But widget album art image quality is poor in canary.
I have enabled high quality album art in both the apps.

![Screenshot_20240803-075834](https://github.com/user-attachments/assets/333f30f7-f5a0-41e1-87ed-c83d4d74a598)
_Thoe this problem is not a priority for me._

**Comment by OxygenCobalt** [comment]
Whoops, I forgot about the downsizing I did in prior attempts to patch this.

Try this @shashankmunda @Mischievous-Loner @Book-reader?

[Auxio_Canary.zip](https://github.com/user-attachments/files/16477866/Auxio_Canary.zip)

**Comment by Mischievous-Loner** [comment]
Well, now the original problem that the square cover art widget didn't load CAME BACK.
IT WORKED WHEN THE QUALITY WAS BAD I.e. previous canary.

**Comment by OxygenCobalt** [comment]
> Well, now the original problem that the square cover art widget didn't load CAME BACK.
> IT WORKED WHEN THE QUALITY WAS BAD I.e. previous canary.

Weird, can you please reproduce the issue on the latest APK and then immediately take a bug report so I can get more info @Mischievous-Loner?

**Comment by Mischievous-Loner** [comment]
https://mega.nz/file/JvA2WRBY#ZMPRkrX80bsi-TOQeNuwXPTslyv8vSWR1g7DZ3RitHY

**Comment by Mischievous-Loner** [comment]
rectangular cover loads while square one doesn't.
It worked in your previous debug but image was crap.

**Comment by OxygenCobalt** [comment]
Okay @Mischievous-Lone @sakuranonamida @Book-reader, try this out. I'm 90% sure this wont work, so please reproduce the error if it exists and send a new bug report. I need the logs to figure out why my mitigation is failing.

[Auxio_Canary.zip](https://github.com/user-attachments/files/16517594/Auxio_Canary.zip)

**Comment by Mischievous-Loner** [comment]
As you said this doesn't work.
Here's the bug report-
https://mega.nz/file/FmZB3TgL#zd2Bl7d7vWJ9AZ1GYwnBVolQkYElPBZi789Jg3ap78Y

**Comment by OxygenCobalt** [comment]
So that was apparently never the bug I was looking for @Mischievous-Loner.

I think it's actually simple: I scale down the image to fit under the limit *assuming* a square image (since the widgets were written before allowing non-square covers). This is now inadequate since non-square covers can still exceed the size limit.

I have to find a way to first see the dimensions of the cover and then dynamically change how it's resized to ensure that it fits under the limit reasonably. This is going to be frustrating and requires some dependency work, so hold tight @sakuranonamida @Book-reader @Mischievous-Loner

**Comment by OxygenCobalt** [comment]
Try this @Mischievous-Loner @Book-reader @sakuranonamida, again no guarantees

[Auxio_Canary.zip](https://github.com/user-attachments/files/16537320/Auxio_Canary.zip)

**Comment by Mischievous-Loner** [comment]
Now Widget doesn't load regardless of the dimensions of the cover image.
Previously at least the rectangular ones worked.
There was no such bug till **version** 3.3.3

**Comment by OxygenCobalt** [comment]
Okay, at this point I am going crazy and just increasing the reduction alongside adding some new debug info to this build @sakuranonamida @Book-reader @Mischievous-Loner 

[Auxio_Canary.zip](https://github.com/user-attachments/files/16554684/Auxio_Canary.zip)

Your build displays the maximum bitmap memory I should see from your device up at the top above the songs/albums/artists/genres/playlists tabs. I know the one it actually is: 6912000. If it differs, that means your OEM modified that code and that's why the widget fails. This is where the second part comes in, the text below the maximum memory is your make and model. If your image size differs, I am giving up and hard-coding in your device into the app with that bitmap limit and capping it there.

**Comment by Book-reader** [comment]
![Screenshot_2024-08-09-13-51-58-19_65b8df5a000978b3161002a299fb7747](https://github.com/user-attachments/assets/a7865476-1a3d-4947-afae-9d6fec9fee0e)

the widgets do work in this version (but are blurry)

![Screenshot_2024-08-09-14-00-30-02_b783bf344239542886fee7b48fa4b892](https://github.com/user-attachments/assets/e4d5b871-5c07-4302-9604-a4a391430d9b)

**Comment by OxygenCobalt** [comment]
Can you try the build from https://github.com/OxygenCobalt/Auxio/issues/828#issuecomment-2274898009, reproduce the broken widget, and then take a [bug report](https://developer.android.com/studio/debug/bug-report) @Book-reader?

**Comment by Book-reader** [comment]
Here:
[bugreport-CPH2273-TP1A.220905.001-2024-08-09-15-28-15.zip](https://github.com/user-attachments/files/16555977/bugreport-CPH2273-TP1A.220905.001-2024-08-09-15-28-15.zip)

**Comment by OxygenCobalt** [comment]
So it does differ on your device @Book-reader: 6912000 instead of 6670080. Regardless, I'm still scaling too much. I just have to fiddle with the reduction in size until I hit the maximum size I can go for that is still at least slightly high quality.

Try this out @Book-reader @Mischievous-Loner, it might be higher quality (or it might just crash again...)
[Auxio_Canary.zip](https://github.com/user-attachments/files/16568340/Auxio_Canary.zip)

**Comment by Mischievous-Loner** [comment]
This one too works for me.
Thoe I didn't notice any quality difference (maybe because of my trash display quality).
Do you still need crash logs from me?
Just a bit confused.

**Comment by Book-reader** [comment]
The album covers do look a lot better in this version.

**Comment by OxygenCobalt** [comment]
Officially shipped in 3.5.3. @Book-reader @Mischievous-Loner @sakuranonamida
