### ISSUE TITLE
Small split-screen UI mode

### ISSUE THREAD

**Issue by portalbyte** [OxygenCobalt/Auxio#829]
### Description

This is probably very niche. My car is crap, so I use my phone for maps and music. I often use Android's split-screen mode - so that I can see my directions and control my music. However, it appears Auxio doesn't scale well at a very small size: either it takes up half the screen, or the text looks weird (see attached screenshots).

![Screenshot_20240715-113050](https://github.com/user-attachments/assets/90023880-a2d8-4aa8-bff3-2697c2d6c86e)
![Screenshot_20240715-113057](https://github.com/user-attachments/assets/b0959a07-ee02-44af-a9bd-9899c321fbba)

### Other implementations

Most other music players don't scale well at this size too, so not sure if its even possible. But Google Maps (which I don't use often) does have a 'driving mode' that has a small music player UI.

![image](https://github.com/user-attachments/assets/5f28f972-efe7-4156-a18d-0290821587eb)

### Benefit

As previously stated, this is probably quite niche (submitting this issue on the off-chance that it might get considered lol). It would likely benefit anyone who would use Auxio in split-screen mode, to easily control their music - such as in a car.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Yeah, I can add another form factor. Didn't expect people to shrink the playback view down this much.

**Comment by OxygenCobalt** [comment]
Alright, I was able to build a marginally usable APP ui for that specific split screen use-case. It allows everything but seeking.

**Comment by OxygenCobalt** [comment]
Care to try this @portalbyte? Let me know what you think.

[Auxio_Canary.zip](https://github.com/user-attachments/files/16322803/Auxio_Canary.zip)

**Comment by portalbyte** [comment]
@OxygenCobalt for some reason, the UI isn't triggering for me.

![Screenshot_20240721-094102](https://github.com/user-attachments/assets/43bb0cb0-4930-410b-bce3-8f1c521f586c)

**Comment by OxygenCobalt** [comment]
Okay, I need to change what dimensions it's activated with then, give me a moment @portalbyte

**Comment by OxygenCobalt** [comment]
Try this @portalbyte?

[Auxio_Canary.zip](https://github.com/user-attachments/files/16369740/Auxio_Canary.zip)

**Comment by jamie6king** [comment]
Hey @OxygenCobalt! Sorry for taking so long to reply, moved flat + new job + school lol (@portalbyte is my old account).

That's much better than before, thank you!

![Screenshot_20240924-085633_Auxio Debug](https://github.com/user-attachments/assets/ce5d64cd-e879-4ecf-9743-4e3f43f7ca98)

Couple of suggestions:
- The 'queue' area takes up a fair amount of space, not sure if it could be reduced / removed?
- Having a playback bar / text would be handy.
- Not sure if this is just my display setting, but the 5 buttons seem kinda small / squished together, so that they're hard to press. Not sure how else to represent them though.
- Might just be my font size but the song text seems a tiny bit small.

No pressure for any of these, but just a couple of suggestions. Love the work, thanks!

**Comment by OxygenCobalt** [comment]
> The 'queue' area takes up a fair amount of space, not sure if it could be reduced / removed?

Not really, it's kind-of required in the app and it's already basically at the minimum reasonable touch target size.

> Having a playback bar / text would be handy.

> Not sure if this is just my display setting, but the 5 buttons seem kinda small / squished together, so that they're hard to press. Not sure how else to represent them though.

> Might just be my font size but the song text seems a tiny bit small.

This is because this "tiny" layout has to accommodate REALLY tiny screens due to how I tested on my Pixel 8. It'd be much harder to do some kind of in-between layout since I don't have your exact dimensions.

Thanks, will keep going w/this
