### ISSUE TITLE
Offer "Folders" view tab when "Include folders" option is used

### ISSUE THREAD

**Issue by lineinthesand** [OxygenCobalt/Auxio#848]
### Description

I read that a Folders view goes against Auxio's tag-based design principle, but hear me out.

When I use the "Include folders" feature, thus consciously deciding from which locations I want my music sourced, such a view could just introduce one higher level when compared to the Artists view, i.e. the levels would be:
1. List of folder sources (as specified in the Include folders settings option), e.g. two folders specified /path/to/flac, /path/to/sdcard
2. Artists
3. Artist's albums
4. Tracks on album 

So, in essence, that would be just another "Filter" for displaying the music by source on storage media.

### Problem solved

I have most of my music organized in a hierarchical folder structure, Artist > Album, but when I browse by Artist view, I get a lot of artists because of compilations and music in folders that are not organized in such a hierarchical manner, which kind of "spams" the Artist view, thus making it harder to actually find the artist/album/track I want.

### Other implementations

In AIMP I have the category "Folders" in addition to the tag-based views of the library (Artists, Albums, Tracks, Genres) but this is more like a file browser which only shows the specified folders and the subfolders it found music in, so, though fulfilling my needs, it is a different approach from what I suggested in this issue.

### Benefit

Well, granted, it's not _everyone_ benefitting from it, but people having a similar hierarchical folder structure or are switching to Auxio as a tag-based player from a player where they were used to browsing by a Folder view.

Yeah, it's my opinion, but I think it would provide a reasonable benefit, while not making the UI/settings page much more complicated (which we want to avoid, right?).

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I think your fundamental problem (Clutter from compilations) can be solved by enabling Hide collaborators in Settings -> Content, care to try that out @lineinthesand?

**Comment by lineinthesand** [comment]
You are right; regarding the compilations, that does make things a little bit better.

However, I suggested that enhancement because I also keep single tracks that I bought (where I don't like the whole album) in a separate folder, as well as music from sources other than my ripped CDs (e.g. whole albums that are only available in digital form). Also, the music in the SD card is different from the one on the internal storage (e.g. lossless and lossy formats, respectively).

As I mentioned, this additional root level should only be (optionally) accessible when you specify more than one "Include" folder. For that case, there could also be a meta folder "All music" in addition to the proposed individual folders.

So in essence, you would have a means to "filter" by individual "sub-libraries", or view all tracks combined from all folders.

This does not necessarily have to be accomplished by new root level folders in the views but could e.g. be selected by pulling down a kind of menu with these "library/folder selection options" when you are in the library view, which currently does not have a pull-down action (e.g. pulling down on the Auxio caption).

**Comment by lineinthesand** [comment]
Sorry, wrong button

**Comment by OxygenCobalt** [comment]
I think I get what you mean, but I don't currently see the appeal of this. It seems quite niche and confuse a lot of users who think there is a folder view but really isn't. I don't think I'm going to go forward with this right now, sorry.

**Comment by landry314** [comment]
a music app needs a folder view. this is what is keeping me from staying with this app as my main user app.

**Comment by OxygenCobalt** [comment]
No, not really @landry314. Let me explain why I refuse this.

All a folder structure does is encode music metadata informally. As a result, every single folder-based library is a snowflake, with their own user-defined format. It could be Artist/Album/Songs, or perhaps it's Album/Discs/Songs, or Genre/Songs, or just a plain pile of songs. Song file names themselves are a fractal of different formats, anything from `Artist_Album_Song.mp4` or `Disc.Track.ogg`.

So, let's say I just go for it. I bolt on a generic file manager onto the app, which takes away time from other functionality and creates an additional maintenance burden given that a file tree would need an entirely different UI flow compared to the rest of the app. Since I will never use the folder view, this functionality will progressively rot and break over time since I will not be able to reasonably test it in daily use.

As time goes on, I'll start getting more feature requests for "small tweaks" to accomodate the endless library shapes. Perhaps "please turn these file names into track/disc numbers" or "merge these artist folders together" or "I want these folders to play as a whole group". Now I either have to deal with a limited folder view or heap on additional complexity in my music loader to deal with these edge cases. More issues, more bugs, more edge cases, more unmaintainablility. Folder based libraries are incompatible with a tag-based music player.

This also does not include what could happen in the future. It's already a nightmare enumerating file trees with the current storage APIs, and Android could very well force me into a new system offering only a flat list of files. Google is moving away from the file system as a usable folder-based structure, and so this feature will continue to rot.

This is intrinsically why I do not add a folder view. It simply does not work with a tag based music player UI. It is a completely different specification.

On the other hand, tags created with kid3, beets, Picard, or anything else are a standardized format I can reasonably work with. The space of configurations are a lot smaller, and the amount of configuration complexity is signifigantly reduced. It's structure agnostic to the actual filesystem I am using. It's maintainable since I use tags myself. This is why I focus on this.

I get that this is annoying, but seriously, I would recommend simply tagging your files. It's so easy nowadays, just add your files to an autotagger like MusicBrainz Picard and it will literally just do all the work for you. There are even Android apps like Automatag that will also do similar autotagging.

**Comment by landry314** [comment]
i dont care about tags. just want to play music from my folders. im using another app, thanks.

**Comment by lineinthesand** [comment]
@landry314 
It is true, this is what I _actually_ miss too but I read that that was dismissed in the first place based on the design philosophy of this project.
