### ISSUE TITLE
Better library state management

### ISSUE THREAD

**Issue by fn-ix** [OxygenCobalt/Auxio#914]
### Description

On a library with over 14k lossless songs and frequent changes, the way Auxio locks interaction while updating the library on app start becomes a noticeable slowdown. The app also often freezes when searching for songs.

### Other implementations

I have no idea how they technically implement it, but Poweramp keeps its UI accessible & snappy and the playback feature functional while updating the library in the background. I assume this does expose it to cases where it’s showing an out-of-date snapshot of the actual filesystem, but this still keeps the app functional for the vast majority of the library, and the loading indicator also lets the user know the database may not be completely accurate for the time being. Searching for songs also never causes any freezes.

### Benefit

The choppy searches and half-minute delays at app start make using this app for people with large, hi-fi libraries unpleasant. It probably doesn’t much affect those with smaller libraries.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Poweramp has something like a decade of full-time engineering effort to somehow make a reliable on-device media database that works around the insanity of the Android media database. I have nowhere near the amount of time, so I just try to make things work to the best extent I can.

I'd guess at a few issues.
- I'm using ExoPlayer's metadata parser, which is annoying and slow because opening files on modern Android is annoying and slow.
    - Secondarily I'm launching literally thousands of threads right now due to a really bad use of their API, which will be fixed in the next major release (4.0.0).
    - And third, I'm wasting a bunch of memory parsing files with larger cover art, which further bogs things down.
    - I should probably move to a native tagging library, but to avoid bloating app size I would need to work on stripping out ExoPlayer's tagging support too, which I have nowhere near enough time to do.
- Everything is in-memory and non-paginated, so there's probably a lot of times where I'm updating a list with like 15k new items and completely obliterating performance, especially on search.
    - I could use a database, but that is more likely to make things worse since SQLite is horribly slow in-practice and would just distribute new delays across the app.
    
I'll make issues tackling scale problems as I'm capable, so I'll be closing this for now as to avoid making a huge megathread for all the problems. Sorry.

**Comment by fn-ix** [comment]
Understood, and thanks for the in-depth explanation!
