### ISSUE TITLE
Swipe to next song

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#94]
another issue (sorry!) but a small one, just notes on how and why could swipe cover to naviage playback work
#### Describe the feature you want to implement:
swiping album cover should ⏪ and ⏩ tracks. 
- as you said it's not possible, the album cover doesn't really need to animate like a carousel. any custom indicator is okay for that if it looks material design-y
- swiping but not releasing should "peek" at the previous and next song title.
![Screenshot_20220307-124254_Oto Music.png](https://user-images.githubusercontent.com/21956756/157028459-8ad86ca3-3e14-4ba7-975e-d3a8382ed823.png)
- any way really this would be implemented is fine or even if not it's not that big of a deal since you can just check queue. if this  is your reason for not implementing this, feel free to close this issue.

#### Why do you think this will improve everyone's usage of Auxio?
- "peeking" at next and previous songs is a good feature from spotify, that in other music players is solved just by having the album covers as carousel, but since in auxio it can't be done this way, it would be still cool to have some other way. plus, the carousel way is slightly bflawed in that you see only the cover, not the name of the next song.
- for example if you swipe and not release the album cover, it could move away to show the next song title (sideways prehaps). 

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
I've done some brainstorming, and I think my way to implement this gesture will be like this:

- As you swipe left/right, the cover art steadily fades as a skip icon grows. 
    - The icon will likely have some kind of background to differentiate it from the cover art.
- Once the "confirmation threshold" (the point at which if you release the app will skip) is reached, the icon will change colors to become more emphasized.
    - The cover art will also change to the cover art of the next/last song, however I'm not sure whether to do a transition as the swipe continues or once the confirmation threshold has been reached. Likely the former, as I already do that with the playback sliding behavior and 
- This way, I can add the gesture and peeking functionality in a stateless manner that does not rely on deprecated UI components and buggy fragment mechanisms. 

I've attached a crude mockup below:
![image](https://user-images.githubusercontent.com/65370175/157139881-bf3abc1f-c637-4047-ae1f-45bb78711474.png)

**Comment by KraXen72** [comment]
this is really cool! better than any other indicator i had in mind! i assume the next song title would appear on the half transparent album cover once peek is added? (correct me if im wrong) 

once again, so cool!

**Comment by OxygenCobalt** [comment]
Plugging [this](https://twitter.com/MishaalRahman/status/1603114355310358530#m) for later. It's more or less what I want to try doing in Auxio.

**Comment by etyarews** [comment]
A suggestion is to use the [material carousel component](https://m3.material.io/components/carousel/)  as the basis for the animation, it fits nicely and I swear I've seen something similar being used at Google I/O where the carousel also changed the content of the screen, almost like a tab.

**Comment by etyarews** [comment]
My suggestion was already out of spec. The Carousel Component should have three visible items at once anyway, where on Auxio you should only show one.

**Comment by OxygenCobalt** [comment]
Added by @Koitharu in #503.

**Comment by KraXen72** [comment]
at last. Thanks a lot!

**Comment by OxygenCobalt** [comment]
So, I might actually hold on releasing this for a bit. I've noticed that this feature is really, *really* buggy. And there's no clear way I can make it less buggy without some significant internal refactors. I'll need more time to stabilize the changeset.

**Comment by OxygenCobalt** [comment]
Specifically, the big issue is the reshuffling behavior. Not only does that change the entire data of the pager, it also changes the current pager position. This prevents me from doing a typical list diff since that will prevent consistent positioning, so either I must:

1. Replace all the items in the pager, which will cause the information to fade out and then fade back in. I have yet to test if disabling item animations would fix this.
2. Do the more drastic action and force-update all of the pager items. If you want a 1 second delay when shuffling, this is how you get a 1 second delay when shuffling.
3. Do some strange dance where I replace all items except for the current one, then move the current item to it's position at the same time I change the pager position.

There's also that issue I'm really scared of where the pager will flicker a little when you scroll past it's range of loaded items. I'm not sure if this is an issue specific with the way I originally tried to implement this around a year ago. It probably is, but I still need to experiment.

I get these are really perfectionist reasons for blocking this, but it's these minor things that add up to produce the poor UX I want to avoid as much as possible. I hope you can understand at least.

**Comment by OxygenCobalt** [comment]
Yeah, despite my best efforts, the ViewPager still won't work reliably. I have to fall back to the gesture system. For the sake of having something, I'll revert the ViewPager and then merge in @Koitharu's #496 as an MVP. It will be a bit of an implicit gesture until I can learn how to make a good animation.

**Comment by OxygenCobalt** [comment]
Closing this as "done" again, but only as an MVP. I'll be spinning off the high quality part to a new issue.
