### ISSUE TITLE
设定“排除文件夹”出现问题

### ISSUE THREAD

**Issue by zbodo** [OxygenCobalt/Auxio#97]
#### Describe the bug/crash:
无法将根目录中的“download” -文件夹添加到排除文件夹中

#### Steps To Reproduce the bug/crash:
1. Go to 设置
2. Click on 排除文件夹
3. Click on Download
4. 无法点击“使用此文件夹”

#### Phone Information:
lineage_sagit-userdebug 11 RQ3A.211001.001 10040362

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
(Sorry if this response is weird, I am using a translator) You seem to be using Android 11, and the file picker on that version and above actually restricts access to directories like "Downloads". I use the system's file picker as Android no longer allows apps to have their own file picker due to "scoped storage" limitations. I don't think I can fix this.

（对不起，如果此响应是奇怪的，我正在使用翻译）您似乎正在使用Android 11，并且该版本的文件选择器实际上限制了对“Downloads”等目录的访问。 我使用系统的文件选择器作为Android不再允许应用程序由于“范围存储”限制而具有自己的文件选择器。 我不认为我可以解决这个问题。
